In [6]:
import pandas as pd 

dataset_target = 'bank_notes'

wd = f'XRF_databases/{dataset_target}/plsda/smeX_ga_optimization_hof.csv'
GA_results = pd.read_csv(wd, sep=';')

# vamos extrair o resumo estatistico de acordo com cada seed (coluna Seed)
# Fitness deve ser media, agregador deve ser moda, metrica deve ser moda, n bags deve ser media, frac_sample_per_bag deve ser media, frac_min_samples_per_predicate deve ser media e replacement deve ser moda
summary_df = GA_results.groupby('Seed').agg({
    'Fitness_RBO_Score': 'mean',
    'Agregador': lambda x: x.mode()[0],
    'Métrica': lambda x: x.mode()[0],
    'N_Bags': 'mean',
    'Frac_Samples_per_Bag': 'mean',
    'Frac_Min_Samples_per_Predicate': 'mean',
    'Replacement': lambda x: x.mode()[0]
}).reset_index()
summary_df

,Seed,Fitness_RBO_Score,Agregador,Métrica,N_Bags,Frac_Samples_per_Bag,Frac_Min_Samples_per_Predicate,Replacement
0,0,0.867876,max,covariance,29.50,0.791420,0.161166,False
1,1,0.864547,sum,covariance,71.55,0.649564,0.121410,True
2,42,0.865966,max,covariance,51.60,0.659263,0.184560,False

In [9]:
dataset_target = 'soil'

wd = f'XRF_databases/{dataset_target}/plsda/smeX_ga_optimization_hof.csv'
GA_results = pd.read_csv(wd, sep=';')

# vamos extrair o resumo estatistico de acordo com cada seed (coluna Seed)
# Fitness deve ser media, agregador deve ser moda, metrica deve ser moda, n bags deve ser media, frac_sample_per_bag deve ser media, frac_min_samples_per_predicate deve ser media e replacement deve ser moda
summary_df = GA_results.groupby('Seed').agg({
    'Fitness_RBO_Score': 'mean',
    'Agregador': lambda x: x.mode()[0],
    'Metric': lambda x: x.mode()[0],
    'N_Bags': 'mean',
    'Frac_Samples_per_Bag': 'mean',
    'Frac_Min_Samples_per_Predicate': 'mean',
    'Replacement': lambda x: x.mode()[0]
}).reset_index()
summary_df

,Seed,Fitness_RBO_Score,Agregador,Metric,N_Bags,Frac_Samples_per_Bag,Frac_Min_Samples_per_Predicate,Replacement
0,0,0.740676,median,MI,72.20,0.664069,0.185365,False
1,1,0.732187,median,MI,136.55,0.737808,0.127440,False