In [1]:
import pandas as pd 

dataset_target = 'bank_notes'

wd = f'XRF_databases/{dataset_target}/plsda/smeX_ga_optimization_hof.csv'
GA_results = pd.read_csv(wd, sep=';')

# vamos extrair o resumo estatistico de acordo com cada seed (coluna Seed)
# Fitness deve ser media, agregador deve ser moda, metrica deve ser moda, n bags deve ser media, frac_sample_per_bag deve ser media, frac_min_samples_per_predicate deve ser media e replacement deve ser moda
summary_df = GA_results.groupby('Seed').agg({
    'Fitness_RBO_Score': 'mean',
    'Agregador': lambda x: x.mode()[0],
    'Métrica': lambda x: x.mode()[0],
    'N_Bags': 'mean',
    'Frac_Samples_per_Bag': 'mean',
    'Frac_Min_Samples_per_Predicate': 'mean',
    'Replacement': lambda x: x.mode()[0]
}).reset_index()
summary_df

,Seed,Fitness_RBO_Score,Agregador,Métrica,N_Bags,Frac_Samples_per_Bag,Frac_Min_Samples_per_Predicate,Replacement
0,0,0.867876,max,covariance,29.50,0.791420,0.161166,False
1,1,0.864547,sum,covariance,71.55,0.649564,0.121410,True
2,42,0.865966,max,covariance,51.60,0.659263,0.184560,False

In [3]:
dataset_target = 'soil'

wd = f'XRF_databases/{dataset_target}/plsda/smeX_ga_optimization_hof.csv'
GA_results = pd.read_csv(wd, sep=';')

# vamos extrair o resumo estatistico de acordo com cada seed (coluna Seed)
# Fitness deve ser media, agregador deve ser moda, metrica deve ser moda, n bags deve ser media, frac_sample_per_bag deve ser media, frac_min_samples_per_predicate deve ser media e replacement deve ser moda
summary_df = GA_results.groupby('Seed').agg({
    'Fitness_RBO_Score': 'mean',
    'Agregador': lambda x: x.mode()[0],
    'Métrica': lambda x: x.mode()[0],
    'N_Bags': 'mean',
    'Frac_Samples_per_Bag': 'mean',
    'Frac_Min_Samples_per_Predicate': 'mean',
    'Replacement': lambda x: x.mode()[0]
}).reset_index()
summary_df

,Seed,Fitness_RBO_Score,Agregador,Métrica,N_Bags,Frac_Samples_per_Bag,Frac_Min_Samples_per_Predicate,Replacement
0,0,0.887398,max,covariance,139.65,0.819919,0.133397,False
1,1,0.918394,sum,covariance,121.85,0.583629,0.096772,False
2,42,0.901405,sum,covariance,125.70,0.561860,0.109713,False

In [4]:
GA_results

,Seed,Rank,Fitness_RBO_Score,Agregador,Métrica,N_Bags,Frac_Samples_per_Bag,Frac_Min_Samples_per_Predicate,Replacement
0,0,1,0.918919,median,covariance,200,0.839112,0.228222,True
1,0,2,0.916997,median,covariance,200,0.839112,0.114790,False
2,0,3,0.908867,median,covariance,200,0.839112,0.249968,False
3,0,4,0.906913,median,covariance,88,0.839112,0.114790,False
4,0,5,0.903552,sum,covariance,29,0.766074,0.152909,True
5,0,6,0.902559,median,covariance,62,0.839112,0.114790,False
6,0,7,0.893250,median,covariance,29,0.546398,0.152909,True
7,0,8,0.891067,median,covariance,200,0.839112,0.176429,False
8,0,9,0.881411,max,covariance,68,0.868557,0.211299,True
9,0,10,0.881411,max,covariance,162,0.868557,0.163426,False
10,0,11,0.879489,max,covariance,162,0.868557,0.056163,False
11,0,12,0.879489,max,covariance,68,0.868557,0.058243,False
12,0,13,0.876401,median,covariance,200,0.838651,0.114790,False
13,0,14,0.875190,median,covariance,200,0.839112,0.109062,False
14,0,15,0.873280,max,covariance,200,0.839112,0.088573,False
15,0,16,0.873280,max,covariance,200,0.839112,0.114790,False
16,0,17,0.873007,max,covariance,113,0.734172,0.056322,True
17,0,18,0.871359,max,covariance,162,0.868557,0.152909,False
18,0,19,0.871359,max,covariance,200,0.879573,0.114790,False
19,0,20,0.870148,max,covariance,50,0.738717,0.122773,True
20,1,1,0.928489,sum,covariance,145,0.571031,0.126756,False
21,1,2,0.925401,sum,covariance,46,0.571031,0.081421,True
22,1,3,0.923479,sum,covariance,59,0.571031,0.081421,False
23,1,4,0.922269,sum,covariance,108,0.571031,0.081421,False
24,1,5,0.922269,sum,covariance,145,0.629350,0.180745,False
25,1,6,0.922269,sum,covariance,145,0.667987,0.081421,False
26,1,7,0.919148,sum,covariance,62,0.571031,0.081421,False
27,1,8,0.919148,sum,covariance,138,0.571031,0.135113,False
28,1,9,0.918875,sum,covariance,125,0.571031,0.081421,False
29,1,10,0.917227,sum,covariance,121,0.571031,0.081421,False
30,1,11,0.916997,sum,covariance,145,0.553238,0.081421,False
31,1,12,0.916997,sum,covariance,145,0.664439,0.081421,False
32,1,13,0.916965,sum,covariance,95,0.571031,0.081421,False
33,1,14,0.916060,sum,covariance,141,0.571031,0.081421,False
34,1,15,0.915787,sum,covariance,149,0.571031,0.081421,False
35,1,16,0.915787,sum,covariance,145,0.571031,0.081421,False
36,1,17,0.913865,sum,covariance,113,0.571031,0.081421,False
37,1,18,0.912928,sum,covariance,145,0.571031,0.190089,True
38,1,19,0.911955,sum,covariance,120,0.571031,0.081421,False
39,1,20,0.911955,sum,covariance,145,0.592108,0.081421,False
40,42,1,0.925401,sum,covariance,174,0.561122,0.103488,False
41,42,2,0.922269,sum,covariance,122,0.561122,0.103488,False
42,42,3,0.921569,sum,covariance,50,0.561122,0.103488,True
43,42,4,0.919148,sum,covariance,86,0.563021,0.103488,False
44,42,5,0.915787,sum,covariance,48,0.561122,0.103488,False
45,42,6,0.915787,sum,covariance,174,0.561122,0.089157,False
46,42,7,0.911955,sum,covariance,174,0.536359,0.073128,False
47,42,8,0.911955,sum,covariance,125,0.561122,0.098365,False
48,42,9,0.910745,sum,covariance,174,0.561122,0.103488,True
49,42,10,0.905735,sum,covariance,103,0.561122,0.103488,False
50,42,11,0.903825,sum,covariance,58,0.561122,0.103488,False
51,42,12,0.900693,sum,covariance,36,0.524019,0.195572,False
52,42,13,0.900693,sum,covariance,47,0.561122,0.209977,False
53,42,14,0.899459,sum,covariance,53,0.561122,0.103488,False
54,42,15,0.879489,sum,covariance,174,0.561122,0.087168,False
55,42,16,0.879489,sum,covariance,197,0.633410,0.103488,False
56,42,17,0.878323,max,covariance,174,0.561122,0.103488,True
57,42,18,0.878323,max,covariance,197,0.561122,0.103488,True
58,42,19,0.876369,sum,covariance,174,0.563559,0.103488,False
59,42,20,0.871086,sum,covariance,174,0.561122,0.095551,False