## Loading data

In [1]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' (one level up) can be imported
import sys
from pathlib import Path # for path manipulations
parent_dir = Path.cwd().parent.parent.resolve() # move two levels up from current working directory
if str(parent_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(parent_dir)) # insert at the start of sys.path to prioritize local modules

# Loading a soil spectral dataset based on X-ray fluorescence (XRF)
data_complete = pd.read_csv(f'{parent_dir}/XRF_databases/bank_notes/plsda/bank_notes.csv', sep=';') # local copy of Toledo 2022 dataset (os ... indica para omitir o caminho longo)
data = data_complete.loc[:, '1':'26.07']

# Split dataset by class and create calibration/prediction sets using Kennard-Stone (as in original pipeline)
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.loc[:, '1':'26.07'], test_size=0.30)  # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.loc[:, '1':'26.07'], test_size=0.30)  # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True)  # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0])  # target for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0])  # target for prediction set

# preprocessings
import preprocessings as prepr  # preprocessing methods for XRF data

Xcalclass_prep, mean_calclass, mean_calclass_poisson  = prepr.poisson(Xcalclass, mc=True)
Xpredclass_prep = ((Xpredclass/np.sqrt(mean_calclass)) - mean_calclass_poisson)

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-28 13:35:04,597 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-28 13:35:04,673 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-28 13:35:04,723 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-28 13:35:04,761 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [2]:
from modeling import svm_optimized

svm_model = svm_optimized(Xcalclass_prep, ycalclass, Xpredclass_prep, ypredclass, aim='classification', kernel='rbf')
svm_model[0]

,Model,Accuracy Cal,Sensitivity Cal,Specificity Cal,CM Cal,Accuracy Pred,Sensitivity Pred,Specificity Pred,CM Pred
0,SVC,0.996479,0.990826,1.0,"[[175, 0], [1, 108]]",1.0,1.0,1.0,"[[76, 0], [0, 47]]"

In [4]:
# calculando a covariancia entre cada variável espectral e a predição do modelo SVM
cov_scores = []
y_pred = svm_model[6]['SVC'].values # using the continuous predictions from SVM, extracting as 1D array
for col in Xcalclass_prep.columns:
    x_values = Xcalclass_prep[col].values
    covariance = np.cov(x_values, y_pred)[0, 1] # covariance between x and y
    cov_scores.append(covariance)
cov_scores_df = pd.DataFrame(cov_scores, index=Xcalclass_prep.columns, columns=['Covariance'])
cov_scores_df = np.abs(cov_scores_df)
cov_scores_df.plot()

In [5]:
X_sv = svm_model[3].support_vectors_            # shape (n_SV, n_features)
alpha_dual = svm_model[3].dual_coef_.ravel()    # shape (n_SV,)

# Calculando os coeficientes p usando os vetores de suporte e os multiplicadores de Lagrange
pvetor = pd.DataFrame({'energia' : Xcalclass.columns,
                       'importance': (X_sv.T) @ alpha_dual})
pvetor['importance'] = np.abs(pvetor['importance'])
pvetor['importance'].plot()

In [6]:
# establishing spectral cuts based on expert knowledge of XRF spectra
spectral_cuts = [
('background1', 1.0, 2.74),
('Ar ka + Ag L', 2.76, 3.47),
('Ca ka', 3.5, 3.91),
('Ca kb', 3.93, 4.24),
('Ti ka', 4.26, 4.72),
('Ti kb', 4.75, 5.13),
('background2', 5.16, 6.12),
('Fe ka', 6.15, 6.76),
('Fe kb', 6.79, 7.32),
('background3', 7.35, 7.78),
('Cu ka', 7.81, 8.29),
('Zn ka', 8.29, 8.80),
('Cu kb', 8.80, 9.26),
('Zn kb', 9.26, 10.00),
('background4', 10.00, 21.46),
('Ag ka scattering', 21.49, 22.71),
('background5', 22.74, 24.52),
('background6', 24.55, 26.07),
]

import explaining as exp
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_sums_df = exp.aggregate_spectral_zones(spectral_zones_class, aggregator='extreme')
predicates_quantiles = exp.predicates_by_quantiles(zone_sums_df, [0.2, 0.4, 0.6, 0.8])
co_occurrence_matrix_df = predicates_quantiles[2]
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_sums_df,
    y_predicted_numeric=y_pred
)

## Pvector and SHAP

In [7]:
# VIP scores por energia
pvector_df = pd.DataFrame({
    'energy': pvetor['energia'],
    'Pvector': pvetor['importance'].values
})
pvector_df = pvector_df.sort_values(by='Pvector', ascending=False).reset_index(drop=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in pvector_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
pvector_df['Zone'] = pvector_df['energy'].map(energy_to_zone_vip)
pvector_unique_df = pvector_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
pvector_unique_df = pvector_unique_df.sort_values(by='Pvector', ascending=False).reset_index(drop=True)
pvector_unique_df
#shap_unique_df = pd.read_csv('shap_bank_notes.csv', sep=';') # loading previously saved shap_unique_df

   energy     Pvector              Zone
0    6.43  185.828282             Fe ka
1    4.54  139.515607             Ti ka
2    8.09   88.880911             Cu ka
3    7.09   59.996151             Fe kb
4    4.93   58.223145             Ti kb
5    3.73   57.054077             Ca ka
6   21.92   54.563418  Ag ka scattering
7    24.8   36.011319       background6
8    8.93   31.932230             Cu kb
9    4.01   21.449267             Ca kb
10  18.02   18.030718       background4
11  23.58   15.838303       background5
12   8.52   14.615837             Zn ka
13   5.97   12.822195       background2
14   7.58   12.645188       background3
15   3.37   12.497974      Ar ka + Ag L
16    1.1   12.376194       background1
17   9.87   11.264983             Zn kb

# **bagging - covariance**

In [8]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = pd.Series(y_pred) # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.01, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graphv2(
        bags_result=all_results_cov[seed]['bags_result'],
        predicate_ranking_dict=all_results_cov[seed]['cov_results_dict'],
        metric_column='Covariance',  # ou 'Covariance' se mudar a métrica
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 3
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total de pares bidirecionais encontrados: 115
Removida aresta Ca ka > -11.34 -> Fe ka > -10.00 (peso 15.6506)
Mantida aresta Fe ka > -10.00 -> Ca ka > -11.34 (peso 70.3297)

======================================================================

Removida aresta Ca ka > -9.12 -> Fe ka > -10.00 (peso 32.4610)
Mantida aresta Fe ka > -10.00 -> Ca ka > -9.12 (peso 50.9860)

======================================================================

Removida aresta Ca ka > -9.12 -> Ca ka > -11.34 (peso 62.9533)
Mantida aresta Ca ka > -11.34 -> Ca ka > -9.12 (peso 99.2274)

======================================================================

Removida aresta Ti ka <= 9.71 -> Fe kb > -3.35 (peso 19.7181)
Mantida aresta Fe kb > -3.35 -> Ti ka <= 9.71 (peso 83.2832)

======================================================================

Removida aresta Ti ka <= 5.26 -> Fe kb > -3.54 (peso 13.8929)
Mantida aresta Fe kb > -3.54 -> Ti ka <= 5.26 (peso 51.3429)

======================================================================

Removida aresta Ca kb > -3.42 -> Fe kb > -3.54 (peso 6.1218)
Mantida aresta Fe kb > -3.54 -> Ca kb > -3.42 (peso 13.0260)

======================================================================

Removida aresta Ca kb > -4.15 -> Ca kb > -3.42 (peso 25.6016)
Mantida aresta Ca kb > -3.42 -> Ca kb > -4.15 (peso 31.1689)

======================================================================

Removida aresta Ti kb <= 5.00 -> Ti kb > -4.43 (peso 8.1663)
Mantida aresta Ti kb > -4.43 -> Ti kb <= 5.00 (peso 16.6258)

======================================================================

Removida aresta Ti kb > -4.43 -> Ca kb > -2.18 (peso 3.9026)
Mantida aresta Ca kb > -2.18 -> Ti kb > -4.43 (peso 8.0923)

======================================================================

Removida aresta Ti kb <= 5.00 -> Ca ka <= 15.99 (peso 8.0500)
Mantida aresta Ca ka <= 15.99 -> Ti kb <= 5.00 (peso 8.3751)

======================================================================

Removida aresta Cu ka > -4.62 -> Ca ka <= 15.99 (peso 3.8860)
Mantida aresta Ca ka <= 15.99 -> Cu ka > -4.62 (peso 14.8481)

======================================================================

Removida aresta Ca ka <= 15.99 -> Ca kb > -2.18 (peso 11.2017)
Mantida aresta Ca kb > -2.18 -> Ca ka <= 15.99 (peso 11.5054)

======================================================================

Removida aresta Cu ka > -4.62 -> Ti kb <= 5.00 (peso 4.0987)
Mantida aresta Ti kb <= 5.00 -> Cu ka > -4.62 (peso 12.2685)

======================================================================

Removida aresta Ca kb > -2.18 -> Cu ka > -4.62 (peso 7.2288)
Mantida aresta Cu ka > -4.62 -> Ca kb > -2.18 (peso 7.3968)

======================================================================

Removida aresta Ti kb <= 2.64 -> Cu ka > -4.31 (peso 5.5064)
Mantida aresta Cu ka > -4.31 -> Ti kb <= 2.64 (peso 9.0279)

======================================================================

Removida aresta Cu ka > -3.81 -> Cu ka > -4.31 (peso 8.6903)
Mantida aresta Cu ka > -4.31 -> Cu ka > -3.81 (peso 18.6816)

======================================================================

Removida aresta Ti kb <= 2.64 -> Cu ka > -3.81 (peso 5.2414)
Mantida aresta Cu ka > -3.81 -> Ti kb <= 2.64 (peso 12.0903)

======================================================================

Removida aresta Ca kb <= 6.30 -> Ti ka > -3.08 (peso 1.6354)
Mantida aresta Ti ka > -3.08 -> Ca kb <= 6.30 (peso 15.6643)

======================================================================

Removida aresta Cu kb > -1.94 -> Ca kb <= 6.30 (peso 1.3767)
Mantida aresta Ca kb <= 6.30 -> Cu kb > -1.94 (peso 7.7533)

======================================================================

Removida aresta Cu kb > -1.94 -> Ti ka <= -3.08 (peso 1.1875)
Mantida aresta Ti ka <= -3.08 -> Cu kb > -1.94 (peso 3.9087)

======================================================================

Removida aresta Ti ka <= -3.08 -> Zn ka <= 2.74 (peso 1.0270)
Mantida aresta Zn ka <= 2.74 -> Ti ka <= -3.08 (peso 1.8909)

======================================================================

Removida aresta Ti ka <= -3.08 -> Zn ka > -1.99 (peso 0.8589)
Mantida aresta Zn ka > -1.99 -> Ti ka <= -3.08 (peso 1.0530)

======================================================================

Removida aresta Cu kb > 1.49 -> Ti ka <= -3.08 (peso 0.8680)
Mantida aresta Ti ka <= -3.08 -> Cu kb > 1.49 (peso 0.9743)

======================================================================

Removida aresta Ti ka <= -3.08 -> Cu kb > -2.22 (peso 1.1569)
Mantida aresta Cu kb > -2.22 -> Ti ka <= -3.08 (peso 1.1890)

======================================================================

Removida aresta Cu kb > -2.22 -> Cu kb > -1.94 (peso 1.1782)
Mantida aresta Cu kb > -1.94 -> Cu kb > -2.22 (peso 5.2191)

======================================================================

Removida aresta Cu kb > -2.22 -> Ti ka > 5.26 (peso 2.4329)
Mantida aresta Ti ka > 5.26 -> Cu kb > -2.22 (peso 3.5488)

======================================================================

Removida aresta Ti ka > 5.26 -> Ti kb > -2.36 (peso 1.1177)
Mantida aresta Ti kb > -2.36 -> Ti ka > 5.26 (peso 3.1708)

======================================================================

Removida aresta Zn ka <= 2.74 -> Zn ka > -1.99 (peso 0.9874)
Mantida aresta Zn ka > -1.99 -> Zn ka <= 2.74 (peso 2.7363)

======================================================================

Removida aresta background2 <= 3.28 -> Zn ka <= 2.74 (peso 0.8130)
Mantida aresta Zn ka <= 2.74 -> background2 <= 3.28 (peso 1.8676)

======================================================================

Removida aresta Cu kb > 1.49 -> background5 <= 2.48 (peso 0.8330)
Mantida aresta background5 <= 2.48 -> Cu kb > 1.49 (peso 1.4340)

======================================================================

Removida aresta Cu kb > 1.49 -> background4 <= 3.24 (peso 0.7035)
Mantida aresta background4 <= 3.24 -> Cu kb > 1.49 (peso 0.9549)

======================================================================

Removida aresta Cu kb > 1.49 -> Ag ka scattering <= 2.57 (peso 0.6669)
Mantida aresta Ag ka scattering <= 2.57 -> Cu kb > 1.49 (peso 1.4568)

======================================================================

Removida aresta Ag ka scattering <= 3.08 -> background5 <= 2.48 (peso 0.7256)
Mantida aresta background5 <= 2.48 -> Ag ka scattering <= 3.08 (peso 1.3213)

======================================================================

Removida aresta background5 <= 2.48 -> background4 <= 2.89 (peso 0.6929)
Mantida aresta background4 <= 2.89 -> background5 <= 2.48 (peso 0.8050)

======================================================================

Removida aresta background6 <= 2.28 -> background5 <= 2.48 (peso 0.6564)
Mantida aresta background5 <= 2.48 -> background6 <= 2.28 (peso 1.4375)

======================================================================

Removida aresta background5 <= 2.48 -> background5 <= 2.88 (peso 0.8972)
Mantida aresta background5 <= 2.88 -> background5 <= 2.48 (peso 1.4253)

======================================================================

Removida aresta background2 <= 3.28 -> background5 <= 2.88 (peso 0.7277)
Mantida aresta background5 <= 2.88 -> background2 <= 3.28 (peso 0.8853)

======================================================================

Removida aresta background4 <= 3.24 -> background2 <= 3.28 (peso 0.6663)
Mantida aresta background2 <= 3.28 -> background4 <= 3.24 (peso 0.8294)

======================================================================

Removida aresta background5 <= 2.88 -> Ag ka scattering <= 3.08 (peso 0.7082)
Mantida aresta Ag ka scattering <= 3.08 -> background5 <= 2.88 (peso 1.4247)

======================================================================

Removida aresta background5 <= 2.88 -> Zn ka <= 2.18 (peso 1.1755)
Mantida aresta Zn ka <= 2.18 -> background5 <= 2.88 (peso 1.2601)

======================================================================

Removida aresta Ti kb > 2.64 -> background5 <= 2.88 (peso 0.5628)
Mantida aresta background5 <= 2.88 -> Ti kb > 2.64 (peso 0.5875)

======================================================================

Removida aresta background5 <= 2.88 -> background6 <= 2.28 (peso 0.5815)
Mantida aresta background6 <= 2.28 -> background5 <= 2.88 (peso 0.6735)

======================================================================

Removida aresta Ag ka scattering <= 2.57 -> Ag ka scattering <= 3.08 (peso 0.4717)
Mantida aresta Ag ka scattering <= 3.08 -> Ag ka scattering <= 2.57 (peso 1.1601)

======================================================================

Removida aresta Ag ka scattering <= 3.08 -> background6 > -2.43 (peso 0.4700)
Mantida aresta background6 > -2.43 -> Ag ka scattering <= 3.08 (peso 0.4733)

======================================================================

Removida aresta Zn ka <= 2.18 -> Ag ka scattering <= 2.57 (peso 0.5832)
Mantida aresta Ag ka scattering <= 2.57 -> Zn ka <= 2.18 (peso 0.6596)

======================================================================

Removida aresta background2 > -2.08 -> Ag ka scattering <= 2.57 (peso 1.1506)
Mantida aresta Ag ka scattering <= 2.57 -> background2 > -2.08 (peso 1.2105)

======================================================================

Removida aresta background2 > -2.08 -> Zn ka <= 2.18 (peso 0.6188)
Mantida aresta Zn ka <= 2.18 -> background2 > -2.08 (peso 0.6278)

======================================================================

Removida aresta background2 > -2.08 -> Ca ka <= -3.71 (peso 0.6001)
Mantida aresta Ca ka <= -3.71 -> background2 > -2.08 (peso 1.2958)

======================================================================

Removida aresta Ag ka scattering <= -1.94 -> background2 > -2.08 (peso 0.4949)
Mantida aresta background2 > -2.08 -> Ag ka scattering <= -1.94 (peso 0.6320)

======================================================================

Removida aresta Ti kb > 2.64 -> background2 > -2.08 (peso 0.5433)
Mantida aresta background2 > -2.08 -> Ti kb > 2.64 (peso 0.5520)

======================================================================

Removida aresta background2 > -2.08 -> background4 <= 3.54 (peso 0.6042)
Mantida aresta background4 <= 3.54 -> background2 > -2.08 (peso 0.6825)

======================================================================

Removida aresta background1 <= 2.53 -> background6 <= 2.28 (peso 0.3606)
Mantida aresta background6 <= 2.28 -> background1 <= 2.53 (peso 0.4276)

======================================================================

Removida aresta background4 <= 3.24 -> background6 <= 2.28 (peso 0.4441)
Mantida aresta background6 <= 2.28 -> background4 <= 3.24 (peso 0.5778)

======================================================================

Removida aresta Ti kb > 2.64 -> Ca ka <= -3.71 (peso 0.5295)
Mantida aresta Ca ka <= -3.71 -> Ti kb > 2.64 (peso 1.1166)

======================================================================

Removida aresta background6 <= 3.20 -> Ti kb > 2.64 (peso 0.4371)
Mantida aresta Ti kb > 2.64 -> background6 <= 3.20 (peso 0.4389)

======================================================================

Removida aresta Ti kb > 2.64 -> Ag ka scattering <= -1.94 (peso 0.4141)
Mantida aresta Ag ka scattering <= -1.94 -> Ti kb > 2.64 (peso 0.4360)

======================================================================

Removida aresta background4 <= 2.89 -> background4 <= 3.24 (peso 0.6200)
Mantida aresta background4 <= 3.24 -> background4 <= 2.89 (peso 1.1788)

======================================================================

Removida aresta background4 <= 3.24 -> background2 <= 2.16 (peso 0.3378)
Mantida aresta background2 <= 2.16 -> background4 <= 3.24 (peso 0.4595)

======================================================================

Removida aresta background4 <= 2.89 -> background6 <= 2.71 (peso 0.3906)
Mantida aresta background6 <= 2.71 -> background4 <= 2.89 (peso 0.4694)

======================================================================

Removida aresta background3 <= 1.70 -> Zn ka > -1.46 (peso 0.3287)
Mantida aresta Zn ka > -1.46 -> background3 <= 1.70 (peso 0.6688)

======================================================================

Removida aresta background6 > -2.43 -> background3 <= 1.70 (peso 0.3228)
Mantida aresta background3 <= 1.70 -> background6 > -2.43 (peso 0.3406)

======================================================================

Removida aresta Ti kb <= -2.36 -> background6 <= 3.20 (peso 0.2477)
Mantida aresta background6 <= 3.20 -> Ti kb <= -2.36 (peso 0.6004)

======================================================================

Removida aresta Cu kb <= 2.72 -> background6 <= 3.20 (peso 0.1847)
Mantida aresta background6 <= 3.20 -> Cu kb <= 2.72 (peso 0.2261)

======================================================================

Removida aresta Ag ka scattering > -2.84 -> Ti kb <= -2.36 (peso 0.2881)
Mantida aresta Ti kb <= -2.36 -> Ag ka scattering > -2.84 (peso 0.3055)

======================================================================

Removida aresta background1 <= 2.53 -> Ti kb <= -2.36 (peso 0.2420)
Mantida aresta Ti kb <= -2.36 -> background1 <= 2.53 (peso 0.2924)

======================================================================

Removida aresta background6 > -2.43 -> background4 <= 3.54 (peso 0.3000)
Mantida aresta background4 <= 3.54 -> background6 > -2.43 (peso 0.7539)

======================================================================

Removida aresta Zn kb <= 1.87 -> background2 <= 2.16 (peso 0.2051)
Mantida aresta background2 <= 2.16 -> Zn kb <= 1.87 (peso 0.3331)

======================================================================

Removida aresta background1 <= 2.22 -> background2 <= 2.16 (peso 0.2758)
Mantida aresta background2 <= 2.16 -> background1 <= 2.22 (peso 0.4412)

======================================================================

Removida aresta background1 > -2.42 -> Ca ka <= -9.12 (peso 0.2208)
Mantida aresta Ca ka <= -9.12 -> background1 > -2.42 (peso 0.2638)

======================================================================

Removida aresta Cu kb <= 2.72 -> Ca ka <= -9.12 (peso 0.2553)
Mantida aresta Ca ka <= -9.12 -> Cu kb <= 2.72 (peso 0.6719)

======================================================================

Removida aresta Cu ka <= -2.19 -> Ca ka <= -9.12 (peso 0.2161)
Mantida aresta Ca ka <= -9.12 -> Cu ka <= -2.19 (peso 0.2525)

======================================================================

Removida aresta Ca ka <= -9.12 -> Ar ka + Ag L > -2.22 (peso 0.2125)
Mantida aresta Ar ka + Ag L > -2.22 -> Ca ka <= -9.12 (peso 0.4725)

======================================================================

Removida aresta background1 > -2.42 -> Cu ka <= -2.19 (peso 0.2335)
Mantida aresta Cu ka <= -2.19 -> background1 > -2.42 (peso 0.2441)

======================================================================

Removida aresta Ca kb <= -2.18 -> Cu ka <= -2.19 (peso 0.1942)
Mantida aresta Cu ka <= -2.19 -> Ca kb <= -2.18 (peso 0.3772)

======================================================================

Removida aresta Ar ka + Ag L > -2.22 -> Cu ka <= -2.19 (peso 0.2387)
Mantida aresta Cu ka <= -2.19 -> Ar ka + Ag L > -2.22 (peso 0.3576)

======================================================================

Removida aresta Cu ka <= -2.19 -> Ag ka scattering > -2.84 (peso 0.2176)

,Predicate_Cov_Seed_0,Predicate_Cov_Seed_1,Predicate_Cov_Seed_2,Predicate_Cov_Seed_3
0,Fe ka > -9.53,Fe ka > -9.53,Fe ka > -9.53,Fe ka > -9.53
1,Fe ka > -9.80,Fe ka > -9.80,Fe ka > -9.80,Fe ka > -9.80
2,Ca ka > -9.12,Fe ka > -10.00,Ca ka > -11.34,Fe ka > -10.00
3,Fe ka > -10.00,Ca ka > -11.34,Fe ka > -10.00,Ca ka > -11.34
4,Ca ka > -11.34,Ca ka > -3.71,Ca ka > -9.12,Ca ka > -3.71
...,...,...,...,...
107,Fe kb <= -3.35,Zn kb > 2.27,Fe kb <= -3.54,background2 > 2.59
108,background1 > 2.22,Cu ka <= -4.31,Cu ka <= -4.31,Fe kb <= -3.35
109,Class_A,Fe kb <= -3.35,Class_A,Class_A
110,Class_B,Class_A,Class_B,Class_B
111,NaN,Class_B,NaN,NaN

In [9]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_cov_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df = lrc_summed_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_cov = lrc_summed_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_cov = lrc_summed_unique_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_cov

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Fe ka > -9.53,19.539555,Fe ka,-9.53,>
1,Ca ka > -11.34,9.899304,Ca ka,-11.34,>
2,Ti ka <= 9.71,7.063821,Ti ka,9.71,<=
3,Fe kb > -3.35,6.795845,Fe kb,-3.35,>
4,Ca kb > -4.15,3.597588,Ca kb,-4.15,>
5,Ti kb > -4.43,2.823385,Ti kb,-4.43,>
6,Cu ka > -4.62,2.220202,Cu ka,-4.62,>
7,Cu kb > -1.94,0.493400,Cu kb,-1.94,>
8,background2 <= 3.28,0.321789,background2,3.28,<=
9,Zn ka > -1.99,0.292483,Zn ka,-1.99,>
10,background5 <= 2.48,0.262154,background5,2.48,<=
11,background4 <= 3.24,0.199849,background4,3.24,<=
12,Ag ka scattering <= 2.57,0.193690,Ag ka scattering,2.57,<=
13,background6 <= 2.28,0.170695,background6,2.28,<=
14,background1 <= 3.00,0.120183,background1,3.00,<=
15,Ar ka + Ag L <= 2.08,0.111674,Ar ka + Ag L,2.08,<=
16,background3 <= 1.70,0.108315,background3,1.70,<=
17,Zn kb <= 1.87,0.097098,Zn kb,1.87,<=
18,Class_B,0.000000,None,None,None

# **Perturbation**

In [10]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = pd.Series(y_pred) # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=svm_model[3],
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        #perturbation_value=0,
        perturbation_mode='mean', # valores entre 'mean' ou 'min'
        stats_source='full', # full indica usar todas as amostras para calcular estatísticas enquanto que 'fold' usa apenas as amostras do fold atual
        #metric='mean_abs_diff',   # Média com sinal (pode ser negativo)
        aim='classification',
        metric='probability_shift', 
        verbose=True
    )

    # Remove todos os valores iguais a zero de todos os bags em perm_results[bag]["Permutation"] e salva como perm_results_thresholded
    # pert_results_seed_thresholded = {}
    # for bag, df in perm_results_seed.items():
    #     # Verifica se é um DataFrame e se a coluna 'Permutation' existe
    #     if isinstance(df, pd.DataFrame) and 'Permutation' in df.columns:
    #         filtered_df = df[df['Permutation'] > 0].copy()
    #         pert_results_seed_thresholded[bag] = filtered_df
    #     else:
    #         # Se não for DataFrame esperado, apenas copia
    #         pert_results_seed_thresholded[bag] = df

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graphv2(
        bags_result=all_results_pert[seed]['bags_result'],
        predicate_ranking_dict=all_results_pert[seed]['pert_results_dict'],
        metric_column='Perturbation',  # ou 'Covariance' se mudar a métrica
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
======================================================================
PERTURBATION IMPORTANCE PARA PREDICADOS
======================================================================
Tipo de tarefa (aim): classification
Modo de perturbação: mean
Fonte das estatísticas: full
Métrica: probability_shift
Total de folds: 10


[Bag_1] Processando 109 predicados...
  Predicado: background1 > -2.42 (n=186)
    Zona: 69 colunas
    Importance: 0.000398
  Predicado: background1 <= 2.22 (n=86)
    Zona: 69 colunas
    Importance: 0.000511
  Predicado: background1 > 2.22 (n=141)
    Zona: 69 colunas
    Importance: 0.000401
  Predicado: background1 <= 2.53 (n=137)
    Zona: 69 colunas
    Importance: 0.000401
  Predicado: background1 > 2.53 (n=90)
    Zona: 69 colunas
    Importance: 0.000506
  Predicado: background1 <= 3.00 (n=180)
    Zona: 69 colunas
    Importance: 0.000425
  Predicado: Ar ka + Ag L > -2.22 (n=184)
    Zona: 29 colunas
    Importance: 0.000238
  Predicado: Ar ka + Ag L <= -1.64 (n=93)
    Zona: 29 colunas
    Importance: 0.000335
  Predicado: Ar ka + Ag L > -1.64 (n=134)
    Zona: 29 colunas
    Importance: 0.000159
  Predicado: Ar ka + Ag L <= 2.08 (n=136)
    Zona: 29 colunas
    Importance: 0.000252
  Predicado: Ar ka + Ag L > 2.08 (n=91)
    Zona: 29 colunas
    Importance: 0.000199
  Predicado: Ar ka + Ag L <= 2.47 (n=181)
    Zona: 29 colunas
    Importance: 0.000218
  Predicado: Ca ka > -11.34 (n=185)
    Zona: 17 colunas
    Importance: 0.011167
  Predicado: Ca ka <= -9.12 (n=89)
    Zona: 17 colunas
    Importance: 0.029415
  Predicado: Ca ka > -9.12 (n=138)
    Zona: 17 colunas
    Importance: 0.009469
  Predicado: Ca ka <= -3.71 (n=132)
    Zona: 17 colunas
    Importance: 0.022775
  Predicado: Ca ka > -3.71 (n=95)
    Zona: 17 colunas
    Importance: 0.009667
  Predicado: Ca ka <= 15.99 (n=181)
    Zona: 17 colunas
    Importance: 0.017185
  Predicado: Ca kb > -4.15 (n=185)
    Zona: 13 colunas
    Importance: 0.000492
  Predicado: Ca kb <= -3.42 (n=89)
    Zona: 13 colunas
    Importance: 0.001670
  Predicado: Ca kb > -3.42 (n=138)
    Zona: 13 colunas
    Importance: 0.000308
  Predicado: Ca kb <= -2.18 (n=134)
    Zona: 13 colunas
    Importance: 0.001309
  Predicado: Ca kb > -2.18 (n=93)
    Zona: 13 colunas
    Importance: 0.000169
  Predicado: Ca kb <= 6.30 (n=181)
    Zona: 13 colunas
    Importance: 0.001008
  Predicado: Ti ka > -11.81 (n=180)
    Zona: 19 colunas
    Importance: 0.062748
  Predicado: Ti ka <= -3.08 (n=93)
    Zona: 19 colunas
    Importance: 0.113287
  Predicado: Ti ka > -3.08 (n=134)
    Zona: 19 colunas
    Importance: 0.022370
  Predicado: Ti ka <= 5.26 (n=137)
    Zona: 19 colunas
    Importance: 0.081526
  Predicado: Ti ka > 5.26 (n=90)
    Zona: 19 colunas
    Importance: 0.026268
  Predicado: Ti ka <= 9.71 (n=182)
    Zona: 19 colunas
    Importance: 0.068408
  Predicado: Ti kb > -4.43 (n=186)
    Zona: 16 colunas
    Importance: 0.003383
  Predicado: Ti kb <= -2.36 (n=91)
    Zona: 16 colunas
    Importance: 0.004987
  Predicado: Ti kb > -2.36 (n=136)
    Zona: 16 colunas
    Importance: 0.001889
  Predicado: Ti kb <= 2.64 (n=137)
    Zona: 16 colunas
    Importance: 0.004021
  Predicado: Ti kb > 2.64 (n=90)
    Zona: 16 colunas
    Importance: 0.001776
  Predicado: Ti kb <= 5.00 (n=179)
    Zona: 16 colunas
    Importance: 0.003542
  Predicado: background2 > -2.08 (n=185)
    Zona: 39 colunas
    Importance: 0.000322
  Predicado: background2 <= 2.16 (n=89)
    Zona: 39 colunas
    Importance: 0.000529
  Predicado: background2 > 2.16 (n=138)
    Zona: 39 colunas
    Importance: 0.000201
  Predicado: background2 <= 2.59 (n=133)
    Zona: 39 colunas
    Importance: 0.000406
  Predicado: background2 > 2.59 (n=94)
    Zona: 39 colunas
    Importance: 0.000221
  Predicado: background2 <= 3.28 (n=182)
    Zona: 39 colunas
    Importance: 0.000343
  Predicado: Fe ka <= -10.00 (n=58)
    Zona: 25 colunas
    Importance: 0.008342
  Predicado: Fe ka > -10.00 (n=169)
    Zona: 25 colunas
    Importance: 0.005348
  Predicado: Fe ka <= -9.80 (n=90)
    Zona: 25 colunas
    Importance: 0.008606
  Predicado: Fe ka > -9.80 (n=137)
    Zona: 25 colunas
    Importance: 0.004475
  Predicado: Fe ka <= -9.53 (n=138)
    Zona: 25 colunas
    Importance: 0.006811
  Predicado: Fe ka > -9.53 (n=89)
    Zona: 25 colunas
    Importance: 0.005030
  Predicado: Fe ka <= -9.25 (n=182)
    Zona: 25 colunas
    Importance: 0.006614
  Predicado: Fe kb > -3.78 (n=195)
    Zona: 22 colunas
    Importance: 0.001691
  Predicado: Fe kb <= -3.54 (n=84)
    Zona: 22 colunas
    Importance: 0.000728
  Predicado: Fe kb > -3.54 (n=143)
    Zona: 22 colunas
    Importance: 0.001970
  Predicado: Fe kb <= -3.35 (n=134)
    Zona: 22 colunas
    Importance: 0.000722
  Predicado: Fe kb > -3.35 (n=93)
    Zona: 22 colunas
    Importance: 0.002646
  Predicado: Fe kb <= -3.14 (n=174)
    Zona: 22 colunas
    Importance: 0.000710
  Predicado: background3 > -1.63 (n=179)
    Zona: 18 colunas
    Importance: 0.000121
  Predicado: background3 <= 1.70 (n=90)
    Zona: 18 colunas
    Importance: 0.000140
  Predicado: background3 > 1.70 (n=137)
    Zona: 18 colunas
    Importance: 0.000130
  Predicado: background3 <= 2.09 (n=129)
    Zona: 18 colunas
    Importance: 0.000129
  Predicado: background3 > 2.09 (n=98)
    Zona: 18 colunas
    Importance: 0.000140
  Predicado: background3 <= 2.47 (n=178)
    Zona: 18 colunas
    Importance: 0.000122
  Predicado: Cu ka > -4.62 (n=182)
    Zona: 20 colunas
    Importance: 0.005974
  Predicado: Cu ka <= -4.31 (n=84)
    Zona: 20 colunas
    Importance: 0.006320
  Predicado: Cu ka > -4.31 (n=143)
    Zona: 20 colunas
    Importance: 0.006236
  Predicado: Cu ka <= -3.81 (n=133)
    Zona: 20 colunas
    Importance: 0.004990
  Predicado: Cu ka > -3.81 (n=94)
    Zona: 20 colunas
    Importance: 0.008075
  Predicado: Cu ka <= -2.19 (n=179)
    Zona: 20 colunas
    Importance: 0.004182
  Predicado: Zn ka > -1.99 (n=186)
    Zona: 21 colunas
    Importance: 0.000143
  Predicado: Zn ka <= -1.46 (n=86)
    Zona: 21 colunas
    Importance: 0.000193
  Predicado: Zn ka > -1.46 (n=141)
    Zona: 21 colunas
    Importance: 0.000103
  Predicado: Zn ka <= 2.18 (n=133)
    Zona: 21 colunas
    Importance: 0.000156
  Predicado: Zn ka > 2.18 (n=94)
    Zona: 21 colunas
    Importance: 0.000111
  Predicado: Zn ka <= 2.74 (n=183)
    Zona: 21 colunas
    Importance: 0.000150
  Predicado: Cu kb > -2.22 (n=188)
    Zona: 19 colunas
    Importance: 0.000435
  Predicado: Cu kb <= -1.94 (n=94)
    Zona: 19 colunas
    Importance: 0.000461
  Predicado: Cu kb > -1.94 (n=133)
    Zona: 19 colunas
    Importance: 0.000453
  Predicado: Cu kb <= 1.49 (n=135)
    Zona: 19 colunas
    Importance: 0.000389
  Predicado: Cu kb > 1.49 (n=92)
    Zona: 19 colunas
    Importance: 0.000554
  Predicado: Cu kb <= 2.72 (n=180)
    Zona: 19 colunas
    Importance: 0.000342
  Predicado: Zn kb > -2.02 (n=183)
    Zona: 30 colunas
    Importance: 0.000135
  Predicado: Zn kb <= 1.87 (n=92)
    Zona: 30 colunas
    Importance: 0.000144
  Predicado: Zn kb > 1.87 (n=135)
    Zona: 30 colunas
    Importance: 0.000141
  Predicado: Zn kb <= 2.27 (n=136)
    Zona: 30 colunas
    Importance: 0.000128
  Predicado: Zn kb > 2.27 (n=91)
    Zona: 30 colunas
    Importance: 0.000163
  Predicado: Zn kb <= 2.73 (n=180)
    Zona: 30 colunas
    Importance: 0.000123
  Predicado: background4 > -3.06 (n=185)
    Zona: 451 colunas
    Importance: 0.001771
  Predicado: background4 <= 2.89 (n=93)
    Zona: 451 colunas
    Importance: 0.002777
  Predicado: background4 > 2.89 (n=134)
    Zona: 451 colunas
    Importance: 0.001858
  Predicado: background4 <= 3.24 (n=138)
    Zona: 451 colunas
    Importance: 0.002392
  Predicado: background4 > 3.24 (n=89)
    Zona: 451 colunas
    Importance: 0.001989
  Predicado: background4 <= 3.54 (n=181)
    Zona: 451 colunas
    Importance: 0.002549
  Predicado: Ag ka scattering > -2.84 (n=185)
    Zona: 49 colunas
    Importance: 0.002411
  Predicado: Ag ka scattering <= -1.94 (n=87)
    Zona: 49 colunas
    Importance: 0.006707
  Predicado: Ag ka scattering > -1.94 (n=140)
    Zona: 49 colunas
    Importance: 0.002607
  Predicado: Ag ka scattering <= 2.57 (n=131)
    Zona: 49 colunas
    Importance: 0.004895
  Predicado: Ag ka scattering > 2.57 (n=96)
    Zona: 49 colunas
    Importance: 0.003200
  Predicado: Ag ka scattering <= 3.08 (n=178)
    Zona: 49 colunas
    Importance: 0.004149
  Predicado: background5 > -2.53 (n=183)
    Zona: 71 colunas
    Importance: 0.000370
  Predicado: background5 <= 2.03 (n=84)
    Zona: 71 colunas
    Importance: 0.000339
  Predicado: background5 > 2.03 (n=143)
    Zona: 71 colunas
    Importance: 0.000380
  Predicado: background5 <= 2.48 (n=131)
    Zona: 71 colunas
    Importance: 0.000405
  Predicado: background5 > 2.48 (n=96)
    Zona: 71 colunas
    Importance: 0.000310
  Predicado: background5 <= 2.88 (n=179)
    Zona: 71 colunas
    Importance: 0.000369
  Predicado: background6 > -2.43 (n=181)
    Zona: 61 colunas
    Importance: 0.000990
  Predicado: background6 <= 2.28 (n=89)
    Zona: 61 colunas
    Importance: 0.002004
  Predicado: background6 > 2.28 (n=138)
    Zona: 61 colunas
    Importance: 0.000865
  Predicado: background6 <= 2.71 (n=137)
    Zona: 61 colunas
    Importance: 0.001557
  Predicado: background6 > 2.71 (n=90)
    Zona: 61 colunas
    Importance: 0.000938
  Predicado: background6 <= 3.20 (n=182)
    Zona: 61 colunas
    Importance: 0.001330

[Bag_2] Processando 109 predicados...
  Predicado: background1 > -2.42 (n=184)
    Zona: 69 colunas
    Importance: 0.000326
  Predicado: background1 <= 2.22 (n=88)
    Zona: 69 colunas
    Importance: 0.000551
  Predicado: background1 > 2.22 (n=139)
    Zona: 69 colunas
    Importance: 0.000293
  Predicado: background1 <= 2.53 (n=136)
    Zona: 69 colunas
    Importance: 0.000417
  Predicado: background1 > 2.53 (n=91)
    Zona: 69 colunas
    Importance: 0.000358
  Predicado: background1 <= 3.00 (n=178)
    Zona: 69 colunas
    Importance: 0.000437
  Predicado: Ar ka + Ag L > -2.22 (n=182)
    Zona: 29 colunas
    Importance: 0.000171
  Predicado: Ar ka + Ag L <= -1.64 (n=95)
    Zona: 29 colunas
    Importance: 0.000174
  Predicado: Ar ka + Ag L > -1.64 (n=132)
    Zona: 29 colunas
    Importance: 0.000159
  Predicado: Ar ka + Ag L <= 2.08 (n=143)
    Zona: 29 colunas
    Importance: 0.000140
  Predicado: Ar ka + Ag L > 2.08 (n=84)
    Zona: 29 colunas
    Importance: 0.000206
  Predicado: Ar ka + Ag L <= 2.47 (n=184)
    Zona: 29 colunas
    Importance: 0.000135
  Predicado: Ca ka > -11.34 (n=185)
    Zona: 17 colunas
    Importance: 0.011678
  Predicado: Ca ka <= -9.12 (n=85)
    Zona: 17 colunas
    Importance: 0.026205
  Predicado: Ca ka > -9.12 (n=142)
    Zona: 17 colunas
    Importance: 0.010023
  Predicado: Ca ka <= -3.71 (n=130)
    Zona: 17 colunas
    Importance: 0.019906
  Predicado: Ca ka > -3.71 (n=97)
    Zona: 17 colunas
    Importance: 0.010958
  Predicado: Ca ka <= 15.99 (n=179)
    Zona: 17 colunas
    Importance: 0.014988
  Predicado: Ca kb > -4.15 (n=184)
    Zona: 13 colunas
    Importance: 0.000512
  Predicado: Ca kb <= -3.42 (n=87)
    Zona: 13 colunas
    Importance: 0.001428
  Predicado: Ca kb > -3.42 (n=140)
    Zona: 13 colunas
    Importance: 0.000342
  Predicado: Ca kb <= -2.18 (n=133)
    Zona: 13 colunas
    Importance: 0.001129
  Predicado: Ca kb > -2.18 (n=94)
    Zona: 13 colunas
    Importance: 0.000234
  Predicado: Ca kb <= 6.30 (n=179)
    Zona: 13 colunas
    Importance: 0.000885
  Predicado: Ti ka > -11.81 (n=177)
    Zona: 19 colunas
    Importance: 0.066182
  Predicado: Ti ka <= -3.08 (n=94)
    Zona: 19 colunas
    Importance: 0.114352
  Predicado: Ti ka > -3.08 (n=133)
    Zona: 19 colunas
    Importance: 0.024818
  Predicado: Ti ka <= 5.26 (n=140)
    Zona: 19 colunas
    Importance: 0.082139
  Predicado: Ti ka > 5.26 (n=87)
    Zona: 19 colunas
    Importance: 0.029315
  Predicado: Ti ka <= 9.71 (n=183)
    Zona: 19 colunas
    Importance: 0.070210
  Predicado: Ti kb > -4.43 (n=182)
    Zona: 16 colunas
    Importance: 0.003247
  Predicado: Ti kb <= -2.36 (n=94)
    Zona: 16 colunas
    Importance: 0.004927
  Predicado: Ti kb > -2.36 (n=133)
    Zona: 16 colunas
    Importance: 0.001625
  Predicado: Ti kb <= 2.64 (n=138)
    Zona: 16 colunas
    Importance: 0.003834
  Predicado: Ti kb > 2.64 (n=89)
    Zona: 16 colunas
    Importance: 0.001688
  Predicado: Ti kb <= 5.00 (n=183)
    Zona: 16 colunas
    Importance: 0.003402
  Predicado: background2 > -2.08 (n=184)
    Zona: 39 colunas
    Importance: 0.000252
  Predicado: background2 <= 2.16 (n=92)
    Zona: 39 colunas
    Importance: 0.000320
  Predicado: background2 > 2.16 (n=135)
    Zona: 39 colunas
    Importance: 0.000214
  Predicado: background2 <= 2.59 (n=135)
    Zona: 39 colunas
    Importance: 0.000266
  Predicado: background2 > 2.59 (n=92)
    Zona: 39 colunas
    Importance: 0.000243
  Predicado: background2 <= 3.28 (n=182)
    Zona: 39 colunas
    Importance: 0.000252
  Predicado: Fe ka <= -10.00 (n=56)
    Zona: 25 colunas
    Importance: 0.008411
  Predicado: Fe ka > -10.00 (n=171)
    Zona: 25 colunas
    Importance: 0.004815
  Predicado: Fe ka <= -9.80 (n=83)
    Zona: 25 colunas
    Importance: 0.008509
  Predicado: Fe ka > -9.80 (n=144)
    Zona: 25 colunas
    Importance: 0.004084
  Predicado: Fe ka <= -9.53 (n=134)
    Zona: 25 colunas
    Importance: 0.006548
  Predicado: Fe ka > -9.53 (n=93)
    Zona: 25 colunas
    Importance: 0.004484
  Predicado: Fe ka <= -9.25 (n=185)
    Zona: 25 colunas
    Importance: 0.006030
  Predicado: Fe kb > -3.78 (n=191)
    Zona: 22 colunas
    Importance: 0.001591
  Predicado: Fe kb <= -3.54 (n=85)
    Zona: 22 colunas
    Importance: 0.000670
  Predicado: Fe kb > -3.54 (n=142)
    Zona: 22 colunas
    Importance: 0.001830
  Predicado: Fe kb <= -3.35 (n=139)
    Zona: 22 colunas
    Importance: 0.000675
  Predicado: Fe kb > -3.35 (n=88)
    Zona: 22 colunas
    Importance: 0.002533
  Predicado: Fe kb <= -3.14 (n=177)
    Zona: 22 colunas
    Importance: 0.000627
  Predicado: background3 > -1.63 (n=180)
    Zona: 18 colunas
    Importance: 0.000088
  Predicado: background3 <= 1.70 (n=92)
    Zona: 18 colunas
    Importance: 0.000145
  Predicado: background3 > 1.70 (n=135)
    Zona: 18 colunas
    Importance: 0.000089
  Predicado: background3 <= 2.09 (n=133)
    Zona: 18 colunas
    Importance: 0.000117
  Predicado: background3 > 2.09 (n=94)
    Zona: 18 colunas
    Importance: 0.000104
  Predicado: background3 <= 2.47 (n=179)
    Zona: 18 colunas
    Importance: 0.000112
  Predicado: Cu ka > -4.62 (n=183)
    Zona: 20 colunas
    Importance: 0.005506
  Predicado: Cu ka <= -4.31 (n=93)
    Zona: 20 colunas
    Importance: 0.005306
  Predicado: Cu ka > -4.31 (n=134)
    Zona: 20 colunas
    Importance: 0.006193
  Predicado: Cu ka <= -3.81 (n=136)
    Zona: 20 colunas
    Importance: 0.004308
  Predicado: Cu ka > -3.81 (n=91)
    Zona: 20 colunas
    Importance: 0.008102
  Predicado: Cu ka <= -2.19 (n=181)
    Zona: 20 colunas
    Importance: 0.003726
  Predicado: Zn ka > -1.99 (n=181)
    Zona: 21 colunas
    Importance: 0.000126
  Predicado: Zn ka <= -1.46 (n=90)
    Zona: 21 colunas
    Importance: 0.000124
  Predicado: Zn ka > -1.46 (n=137)
    Zona: 21 colunas
    Importance: 0.000112
  Predicado: Zn ka <= 2.18 (n=134)
    Zona: 21 colunas
    Importance: 0.000114
  Predicado: Zn ka > 2.18 (n=93)
    Zona: 21 colunas
    Importance: 0.000120
  Predicado: Zn ka <= 2.74 (n=181)
    Zona: 21 colunas
    Importance: 0.000117
  Predicado: Cu kb > -2.22 (n=191)
    Zona: 19 colunas
    Importance: 0.000383
  Predicado: Cu kb <= -1.94 (n=88)
    Zona: 19 colunas
    Importance: 0.000410
  Predicado: Cu kb > -1.94 (n=139)
    Zona: 19 colunas
    Importance: 0.000400
  Predicado: Cu kb <= 1.49 (n=135)
    Zona: 19 colunas
    Importance: 0.000328
  Predicado: Cu kb > 1.49 (n=92)
    Zona: 19 colunas
    Importance: 0.000516
  Predicado: Cu kb <= 2.72 (n=182)
    Zona: 19 colunas
    Importance: 0.000294
  Predicado: Zn kb > -2.02 (n=180)
    Zona: 30 colunas
    Importance: 0.000146
  Predicado: Zn kb <= 1.87 (n=92)
    Zona: 30 colunas
    Importance: 0.000141
  Predicado: Zn kb > 1.87 (n=135)
    Zona: 30 colunas
    Importance: 0.000153
  Predicado: Zn kb <= 2.27 (n=133)
    Zona: 30 colunas
    Importance: 0.000129
  Predicado: Zn kb > 2.27 (n=94)
    Zona: 30 colunas
    Importance: 0.000175
  Predicado: Zn kb <= 2.73 (n=181)
    Zona: 30 colunas
    Importance: 0.000125
  Predicado: background4 > -3.06 (n=181)
    Zona: 451 colunas
    Importance: 0.001160
  Predicado: background4 <= 2.89 (n=91)
    Zona: 451 colunas
    Importance: 0.002872
  Predicado: background4 > 2.89 (n=136)
    Zona: 451 colunas
    Importance: 0.001169
  Predicado: background4 <= 3.24 (n=138)
    Zona: 451 colunas
    Importance: 0.002396
  Predicado: background4 > 3.24 (n=89)
    Zona: 451 colunas
    Importance: 0.001008
  Predicado: background4 <= 3.54 (n=182)
    Zona: 451 colunas
    Importance: 0.002051
  Predicado: Ag ka scattering > -2.84 (n=183)
    Zona: 49 colunas
    Importance: 0.002123
  Predicado: Ag ka scattering <= -1.94 (n=96)
    Zona: 49 colunas
    Importance: 0.006569
  Predicado: Ag ka scattering > -1.94 (n=131)
    Zona: 49 colunas
    Importance: 0.002271
  Predicado: Ag ka scattering <= 2.57 (n=138)
    Zona: 49 colunas
    Importance: 0.005090
  Predicado: Ag ka scattering > 2.57 (n=89)
    Zona: 49 colunas
    Importance: 0.002536
  Predicado: Ag ka scattering <= 3.08 (n=178)
    Zona: 49 colunas
    Importance: 0.004236
  Predicado: background5 > -2.53 (n=182)
    Zona: 71 colunas
    Importance: 0.000329
  Predicado: background5 <= 2.03 (n=93)
    Zona: 71 colunas
    Importance: 0.000337
  Predicado: background5 > 2.03 (n=134)
    Zona: 71 colunas
    Importance: 0.000332
  Predicado: background5 <= 2.48 (n=138)
    Zona: 71 colunas
    Importance: 0.000382
  Predicado: background5 > 2.48 (n=89)
    Zona: 71 colunas
    Importance: 0.000259
  Predicado: background5 <= 2.88 (n=183)
    Zona: 71 colunas
    Importance: 0.000339
  Predicado: background6 > -2.43 (n=183)
    Zona: 61 colunas
    Importance: 0.000720
  Predicado: background6 <= 2.28 (n=84)
    Zona: 61 colunas
    Importance: 0.001851
  Predicado: background6 > 2.28 (n=143)
    Zona: 61 colunas
    Importance: 0.000786
  Predicado: background6 <= 2.71 (n=134)
    Zona: 61 colunas
    Importance: 0.001421
  Predicado: background6 > 2.71 (n=93)
    Zona: 61 colunas
    Importance: 0.000833
  Predicado: background6 <= 3.20 (n=181)
    Zona: 61 colunas
    Importance: 0.001229

[Bag_3] Processando 108 predicados...
  Predicado: background1 > -2.42 (n=186)
    Zona: 69 colunas
    Importance: 0.000609
  Predicado: background1 <= 2.22 (n=89)
    Zona: 69 colunas
    Importance: 0.000558
  Predicado: background1 > 2.22 (n=138)
    Zona: 69 colunas
    Importance: 0.000670
  Predicado: background1 <= 2.53 (n=138)
    Zona: 69 colunas

    Predicate_pert_Seed_0 Predicate_pert_Seed_1
0          Ti ka <= -3.08        Ti ka <= -3.08
1           Ti ka <= 5.26         Ti ka <= 5.26
2           Ti ka <= 9.71         Ti ka <= 9.71
3          Ti ka > -11.81        Ti ka > -11.81
4          Ca ka <= -9.12        Ca ka <= -9.12
..                    ...                   ...
107          Zn ka > 2.18   background3 <= 1.70
108    background3 > 1.70         Zn kb <= 2.73
109               Class_A   background3 <= 2.09
110               Class_B               Class_A
111                   NaN               Class_B

[112 rows x 2 columns]

In [12]:
all_results_pert[0]['pert_results_dict']['Bag_9']

NameError: name 'all_results_pert' is not defined

In [32]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_pert_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df = lrc_summed_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_pert = lrc_summed_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_pert = lrc_summed_unique_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_pert

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Ti ka <= -3.08,19.951264,Ti ka,-3.08,<=
1,Ca ka <= -9.12,5.980030,Ca ka,-9.12,<=
2,Fe ka <= -10.00,1.064709,Fe ka,-10.00,<=
3,Ag ka scattering <= -1.94,0.876688,Ag ka scattering,-1.94,<=
4,Cu ka <= -4.31,0.786209,Cu ka,-4.31,<=
5,Ti kb <= -2.36,0.625074,Ti kb,-2.36,<=
6,background4 <= 2.89,0.501688,background4,2.89,<=
7,Fe kb > -3.14,0.465026,Fe kb,-3.14,>
8,background6 <= 2.28,0.414660,background6,2.28,<=
9,Ca kb <= -3.42,0.335439,Ca kb,-3.42,<=
10,background1 > 2.53,0.080554,background1,2.53,>
11,Cu kb > 1.49,0.040906,Cu kb,1.49,>
12,background5 <= 2.48,0.038757,background5,2.48,<=
13,background2 <= 2.16,0.035211,background2,2.16,<=
14,Ar ka + Ag L <= -1.64,0.028316,Ar ka + Ag L,-1.64,<=
15,Zn kb > 2.27,0.021536,Zn kb,2.27,>
16,background3 > 2.09,0.016991,background3,2.09,>
17,Zn ka <= -1.46,0.016982,Zn ka,-1.46,<=
18,Class_A,0.000000,None,None,None

In [33]:
import numpy as np

max_len = max(
    len(pvector_unique_df['Zone']),
    #len(shap_unique_df['Zone']),
    len(lrc_summed_unique_df_pert['Zone']),
    len(lrc_summed_unique_df_cov['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'pvector': pad_list(pvector_unique_df['Zone'], max_len),
    #'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'LRC_perturbation' : pad_list(lrc_summed_unique_df_pert['Zone'], max_len),
    'LRC_covariance' : pad_list(lrc_summed_unique_df_cov['Zone'], max_len),
})

#features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

             pvector  LRC_perturbation    LRC_covariance
0              Fe ka             Ti ka             Fe ka
1              Ti ka             Ca ka             Ca ka
2              Cu ka             Fe ka             Ti ka
3              Fe kb  Ag ka scattering             Fe kb
4              Ti kb             Cu ka             Ca kb
5              Ca ka             Ti kb             Ti kb
6   Ag ka scattering       background4             Cu ka
7        background6             Fe kb             Cu kb
8              Cu kb       background6       background2
9              Ca kb             Ca kb             Zn ka
10       background4       background1       background5
11       background5             Cu kb       background4
12             Zn ka       background5  Ag ka scattering
13       background2       background2       background6
14       background3      Ar ka + Ag L       background1
15      Ar ka + Ag L             Zn kb      Ar ka + Ag L
16       background1       background3       background3
17             Zn kb             Zn ka             Zn kb
18              None              None              None

In [34]:
# RBO (Rank-Biased Overlap) para comparar rankings
import rbo
rbo_results = {}
reference_list = [x for x in features_importance['pvector'].tolist() if x is not None]
methods = ['LRC_covariance', 'LRC_perturbation']
for method in methods:
    compare_list = [x for x in features_importance[method].tolist() if x is not None]
    # Truncate both lists to the same length (minimum of both)
    min_len = min(len(reference_list), len(compare_list))
    ref_trunc = reference_list[:min_len]
    cmp_trunc = compare_list[:min_len]
    score = rbo.RankingSimilarity(ref_trunc, cmp_trunc).rbo(p=0.7, k=10)
    rbo_results[method] = score
rbo_results = pd.DataFrame(list(rbo_results.items()), columns=['Method','RBO_Score'])
rbo_results.insert(0, 'Reference', 'pvector')
rbo_results.sort_values(by='RBO_Score', ascending=False, inplace=True)
#rbo_results.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_results

  Reference            Method  RBO_Score
0   pvector    LRC_covariance   0.737329
1   pvector  LRC_perturbation   0.417824