# **Model**

# **XRF milk database**

In [1]:
# generating synthetic spectra with different noise levels
import pandas as pd
import numpy as np
import kennard_stone as ks

# Add parent directory to sys.path so local module 'synthetic' (one level up) can be imported
import sys
from pathlib import Path # for path manipulations
parent_dir = Path.cwd().parent.parent.resolve() # move two levels up from current working directory
if str(parent_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(parent_dir)) # insert at the start of sys.path to prioritize local modules

from synthetic import generate_synthetic_spectral_data

config = [
    {
        'nome': 'A',
        'n_amostras': 156,
        'picos': [250, 380, 550, 700, 850],  # 4 picos
        'amp_media': 1.0,
        'amp_std': 0.3,
        'larg_media': 15.0,
        'larg_std': 2.0,
        'ruido_std': 0.04
    },
    {
        'nome': 'B',
        'n_amostras': 146,
        'picos': [50, 250, 380, 550, 850],  # 3 picos (sem pico em 550)
        'amp_media': 1.4,
        'amp_std': 0.5,
        'larg_media': 15.0,
        'larg_std': 1.8,
        'ruido_std': 0.035
    }
]

data_complete = generate_synthetic_spectral_data(
    configuracao_classes=config,
    n_pontos=500,
    x_min=1,
    x_max=1000,
    seed=0
)

import pandas as pd
pd.options.plotting.backend = 'plotly' # setting plotly as the backend for pandas plotting 

# Split dataset by class and create calibration/prediction sets using Kennard-Stone (as in original pipeline)
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.iloc[:, 1:], test_size=0.30)  # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.iloc[:, 1:], test_size=0.30)  # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True)  # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0])  # target for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0])  # target for prediction set

# Xcalclass_prep = Xcalclass.copy()
# Xpredclass_prep = Xpredclass.copy()

# preprocessings
import preprocessings as prepr  # preprocessing methods
Xcalclass_prep, mean_calclass  = prepr.mc(Xcalclass)
Xpredclass_prep = Xpredclass - mean_calclass

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-29 06:53:52,002 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-29 06:53:52,026 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-29 06:53:52,069 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-29 06:53:52,088 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [ ]:
from modeling import svm_optimized

svm_model = svm_optimized(Xcalclass_prep, ycalclass, Xpredclass_prep, ypredclass, aim='classification', kernel='rbf')
svm_model[0]

,Model,Accuracy Cal,Sensitivity Cal,Specificity Cal,CM Cal,Accuracy Pred,Sensitivity Pred,Specificity Pred,CM Pred
0,SVC,1.0,1.0,1.0,"[[109, 0], [0, 102]]",1.0,1.0,1.0,"[[47, 0], [0, 44]]"

In [4]:
# calculando a covariancia entre cada variável espectral e a predição do modelo SVM
y_pred = svm_model[4]['SVC'].values # using the continuous predictions from SVM, extracting as 1D array
cov_scores = []
for col in Xcalclass_prep.columns:
    x_values = Xcalclass_prep[col].values
    covariance = np.cov(x_values, y_pred)[0, 1] # covariance between x and y
    cov_scores.append(covariance)
cov_scores_df = pd.DataFrame(cov_scores, index=Xcalclass_prep.columns, columns=['Covariance'])
cov_scores_df = np.abs(cov_scores_df)
cov_scores_df.plot()

In [5]:
X_sv = svm_model[3].support_vectors_            # shape (n_SV, n_features)
alpha_dual = svm_model[3].dual_coef_.ravel()    # shape (n_SV,)

# Calculando os coeficientes p usando os vetores de suporte e os multiplicadores de Lagrange
pvetor = pd.DataFrame({'energia' : Xcalclass.columns,
                       'importance': (X_sv.T) @ alpha_dual})
pvetor['importance'] = np.abs(pvetor['importance'])
pvetor['importance'].plot()

In [6]:
# establishing spectral cuts based on expert knowledge of XRF spectra
spectral_cuts = [
('F1', 1.0, 100.0),
('background1', 100.0, 200.0),
('F2', 200.0, 300.0),
('background2', 300.0, 330.0),
('F3', 330.0, 430.0),
('background3', 430.0, 500.0),
('F4', 500.0, 600.0),
('background4', 600.0, 660.0),
('F5', 660.0, 750.0),
('background5', 750.0, 815.0),
('F6', 815.0, 890.0),
('background6', 890.0, 1000.0)
]

In [7]:
import explaining as exp
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_sums_df = exp.aggregate_spectral_zones(spectral_zones_class, aggregator='extreme')
predicates_quantiles = exp.predicates_by_quantiles(zone_sums_df, [0.2, 0.4, 0.6, 0.8])
co_occurrence_matrix_df = predicates_quantiles[2]
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_sums_df,
    y_predicted_numeric=y_pred
)

## Pvector and SHAP

In [8]:
# VIP scores por energia
pvector_df = pd.DataFrame({
    'energy': pvetor['energia'],
    'Pvector': pvetor['importance'].values
})
pvector_df = pvector_df.sort_values(by='Pvector', ascending=False).reset_index(drop=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in pvector_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
pvector_df['Zone'] = pvector_df['energy'].map(energy_to_zone_vip)
pvector_unique_df = pvector_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
pvector_unique_df = pvector_unique_df.sort_values(by='Pvector', ascending=False).reset_index(drop=True)
pvector_unique_df
shap_unique_df = pd.read_csv('shap_synthetic.csv', sep=';') # loading previously saved shap_unique_df

# permutation

In [9]:
# Permutation importance baseado em mudança nas probabilidades previstas (predict_proba)
# Medimos a média da diferença absoluta entre as probabilidades originais e as probabilidades
# obtidas após permutar cada variável. Isso fornece uma métrica contínua de importância.
n_repeats = 10
rng = np.random.RandomState(42)
# Probabilidades base (classe 'B' mapeada para 1)
baseline_proba = svm_model[3].predict_proba(Xcalclass_prep)[:, 1]
importance_list = []
X_arr = Xcalclass_prep.copy()
for col in Xcalclass_prep.columns:
    diffs = []
    for _ in range(n_repeats):
        X_perm = X_arr.copy()
        X_perm[col] = rng.permutation(X_perm[col].values)
        perm_proba = svm_model[3].predict_proba(X_perm)[:, 1]
        diffs.append(np.mean(np.abs(baseline_proba - perm_proba)))
    importance_list.append(np.mean(diffs))

permutation_df = pd.DataFrame({
    'energy': Xcalclass_prep.columns,
    'Permutation_importance_proba': importance_list
})
permutation_df.sort_values(by='Permutation_importance_proba', ascending=False, inplace=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in permutation_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
permutation_df['Zone'] = permutation_df['energy'].map(energy_to_zone_vip)
permutation_unique_df = permutation_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
permutation_unique_df = permutation_unique_df.sort_values(by='Permutation_importance_proba', ascending=False)
permutation_unique_df

                energy  Permutation_importance_proba         Zone
0   49.048096192384776                      0.003943           F1
1    699.6993987975952                      0.001277           F5
2    847.8476953907816                      0.000612           F6
3    379.3787575150301                      0.000526           F3
4    549.5490981963928                      0.000506           F4
5     249.248496993988                      0.000443           F2
6   109.10821643286573                      0.000010  background1
7    315.3146292585171                      0.000010  background2
8    791.7915831663327                      0.000010  background5
9    605.6052104208417                      0.000008  background4
10   911.9118236472947                      0.000008  background6
11   441.4408817635271                      0.000006  background3

# **bagging - covariance**

In [17]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = pd.Series(y_pred) # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.0001, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graphv2(
        bags_result=all_results_cov[seed]['bags_result'],
        predicate_ranking_dict=all_results_cov[seed]['cov_results_dict'],
        metric_column='Covariance',  # ou 'Covariance' se mudar a métrica
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 75 | Descartados: 21
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.0001

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 75 | Descartados: 21
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.0001

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 75 | Descartados: 21
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 75 | Descartados: 21
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.0001

======================================================================
Processando semente: 3
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.0001

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total de pares bidirecionais encontrados: 96
Removida aresta F1 <= 0.83 -> F1 > -0.69 (peso 0.7655)
Mantida aresta F1 > -0.69 -> F1 <= 0.83 (peso 1.3117)

======================================================================

Removida aresta F5 > -0.54 -> F1 > -0.69 (peso 0.4979)
Mantida aresta F1 > -0.69 -> F5 > -0.54 (peso 0.7374)

======================================================================

Removida aresta F6 > -0.42 -> F2 > -0.45 (peso 0.1064)
Mantida aresta F2 > -0.45 -> F6 > -0.42 (peso 0.2289)

======================================================================

Removida aresta F4 > -0.24 -> F2 > -0.45 (peso 0.1059)
Mantida aresta F2 > -0.45 -> F4 > -0.24 (peso 0.3368)

======================================================================

Removida aresta F2 > -0.45 -> F4 > -0.47 (peso 0.1055)
Mantida aresta F4 > -0.47 -> F2 > -0.45 (peso 0.2245)

======================================================================

Removida aresta F3 > -0.43 -> F4 > -0.24 (peso 0.0982)
Mantida aresta F4 > -0.24 -> F3 > -0.43 (peso 0.1128)

======================================================================

Removida aresta F3 > -0.23 -> F3 > -0.43 (peso 0.1859)
Mantida aresta F3 > -0.43 -> F3 > -0.23 (peso 0.1873)

======================================================================

Removida aresta F3 > -0.43 -> F6 > -0.42 (peso 0.0978)
Mantida aresta F6 > -0.42 -> F3 > -0.43 (peso 0.1929)

======================================================================

Removida aresta F3 > -0.43 -> F6 > -0.25 (peso 0.0886)
Mantida aresta F6 > -0.25 -> F3 > -0.43 (peso 0.1767)

======================================================================

Removida aresta F4 > -0.47 -> F4 > -0.24 (peso 0.1073)
Mantida aresta F4 > -0.24 -> F4 > -0.47 (peso 0.5204)

======================================================================

Removida aresta F4 > -0.47 -> F6 > -0.42 (peso 0.0958)
Mantida aresta F6 > -0.42 -> F4 > -0.47 (peso 0.1015)

======================================================================

Removida aresta F6 > 0.13 -> F3 > -0.23 (peso 0.0899)
Mantida aresta F3 > -0.23 -> F6 > 0.13 (peso 0.3525)

======================================================================

Removida aresta F6 > 0.13 -> F6 > -0.42 (peso 0.0887)
Mantida aresta F6 > -0.42 -> F6 > 0.13 (peso 0.0966)

======================================================================

Removida aresta F6 > -0.25 -> F6 > 0.13 (peso 0.0842)
Mantida aresta F6 > 0.13 -> F6 > -0.25 (peso 0.2573)

======================================================================

Removida aresta F6 > 0.13 -> F1 <= 0.22 (peso 0.0845)
Mantida aresta F1 <= 0.22 -> F6 > 0.13 (peso 0.1611)

======================================================================

Removida aresta F2 > -0.23 -> F6 > -0.42 (peso 0.1909)
Mantida aresta F6 > -0.42 -> F2 > -0.23 (peso 0.1946)

======================================================================

Removida aresta F6 > -0.25 -> F2 > -0.23 (peso 0.0884)
Mantida aresta F2 > -0.23 -> F6 > -0.25 (peso 0.2539)

======================================================================

Removida aresta F5 <= 0.24 -> F2 > -0.23 (peso 0.0772)
Mantida aresta F2 > -0.23 -> F5 <= 0.24 (peso 0.1583)

======================================================================

Removida aresta F2 > -0.23 -> F1 <= 0.22 (peso 0.0757)
Mantida aresta F1 <= 0.22 -> F2 > -0.23 (peso 0.1686)

======================================================================

Removida aresta F2 > 0.17 -> F1 <= 0.22 (peso 0.0646)
Mantida aresta F1 <= 0.22 -> F2 > 0.17 (peso 0.1495)

======================================================================

Removida aresta F2 > 0.17 -> F3 > 0.14 (peso 0.1235)
Mantida aresta F3 > 0.14 -> F2 > 0.17 (peso 0.1813)

======================================================================

Removida aresta F3 > 0.14 -> F3 <= 0.44 (peso 0.0525)
Mantida aresta F3 <= 0.44 -> F3 > 0.14 (peso 0.2222)

======================================================================

Removida aresta F3 <= 0.44 -> F4 > 0.18 (peso 0.0521)
Mantida aresta F4 > 0.18 -> F3 <= 0.44 (peso 0.2611)

======================================================================

Removida aresta F4 <= 0.50 -> F4 > 0.18 (peso 0.0417)
Mantida aresta F4 > 0.18 -> F4 <= 0.50 (peso 0.0990)

======================================================================

Removida aresta F2 <= 0.40 -> F4 > 0.18 (peso 0.0393)
Mantida aresta F4 > 0.18 -> F2 <= 0.40 (peso 0.0806)

======================================================================

Removida aresta F3 <= 0.14 -> F4 <= 0.50 (peso 0.0245)
Mantida aresta F4 <= 0.50 -> F3 <= 0.14 (peso 0.0589)

======================================================================

Removida aresta F4 <= 0.50 -> F2 <= 0.40 (peso 0.0671)
Mantida aresta F2 <= 0.40 -> F4 <= 0.50 (peso 0.1469)

======================================================================

Removida aresta F6 <= 0.42 -> F4 <= 0.50 (peso 0.0277)
Mantida aresta F4 <= 0.50 -> F6 <= 0.42 (peso 0.0554)

======================================================================

Removida aresta background4 > -0.09 -> F3 <= 0.14 (peso 0.0150)
Mantida aresta F3 <= 0.14 -> background4 > -0.09 (peso 0.0696)

======================================================================

Removida aresta F3 <= 0.14 -> F6 <= 0.42 (peso 0.0586)
Mantida aresta F6 <= 0.42 -> F3 <= 0.14 (peso 0.0599)

======================================================================

Removida aresta F3 <= 0.14 -> F6 <= 0.13 (peso 0.0141)
Mantida aresta F6 <= 0.13 -> F3 <= 0.14 (peso 0.0357)

======================================================================

Removida aresta F6 <= 0.13 -> F2 <= 0.17 (peso 0.0145)
Mantida aresta F2 <= 0.17 -> F6 <= 0.13 (peso 0.0682)

======================================================================

Removida aresta F2 <= 0.17 -> F6 <= 0.42 (peso 0.0232)
Mantida aresta F6 <= 0.42 -> F2 <= 0.17 (peso 0.0247)

======================================================================

Removida aresta F4 <= -0.24 -> background4 > -0.09 (peso 0.0132)
Mantida aresta background4 > -0.09 -> F4 <= -0.24 (peso 0.0155)

======================================================================

Removida aresta background4 > -0.09 -> F4 <= 0.18 (peso 0.0146)
Mantida aresta F4 <= 0.18 -> background4 > -0.09 (peso 0.0195)

======================================================================

Removida aresta F6 <= 0.42 -> F4 <= -0.24 (peso 0.0191)
Mantida aresta F4 <= -0.24 -> F6 <= 0.42 (peso 0.0356)

======================================================================

Removida aresta F4 <= -0.24 -> F4 <= 0.18 (peso 0.0091)
Mantida aresta F4 <= 0.18 -> F4 <= -0.24 (peso 0.0104)

======================================================================

Removida aresta F6 <= 0.13 -> F6 <= 0.42 (peso 0.0186)
Mantida aresta F6 <= 0.42 -> F6 <= 0.13 (peso 0.0210)

======================================================================

Removida aresta background6 <= 0.10 -> F6 <= 0.13 (peso 0.0127)
Mantida aresta F6 <= 0.13 -> background6 <= 0.10 (peso 0.0127)

======================================================================

Removida aresta background1 > -0.10 -> background3 > -0.08 (peso 0.0223)
Mantida aresta background3 > -0.08 -> background1 > -0.10 (peso 0.0226)

======================================================================

Removida aresta background6 <= 0.08 -> background1 > -0.10 (peso 0.0082)
Mantida aresta background1 > -0.10 -> background6 <= 0.08 (peso 0.0104)

======================================================================

Removida aresta background1 > -0.10 -> background1 <= 0.08 (peso 0.0092)
Mantida aresta background1 <= 0.08 -> background1 > -0.10 (peso 0.0111)

======================================================================

Removida aresta background3 > -0.09 -> background1 > -0.08 (peso 0.0077)
Mantida aresta background1 > -0.08 -> background3 > -0.09 (peso 0.0141)

======================================================================

Removida aresta background1 > -0.08 -> background3 <= 0.07 (peso 0.0073)
Mantida aresta background3 <= 0.07 -> background1 > -0.08 (peso 0.0100)

======================================================================

Removida aresta background1 > -0.08 -> background1 <= 0.08 (peso 0.0086)
Mantida aresta background1 <= 0.08 -> background1 > -0.08 (peso 0.0090)

======================================================================

Removida aresta background1 <= 0.08 -> background3 > -0.08 (peso 0.0115)
Mantida aresta background3 > -0.08 -> background1 <= 0.08 (peso 0.0215)

======================================================================

Removida aresta background3 > -0.08 -> F3 <= -0.23 (peso 0.0108)
Mantida aresta F3 <= -0.23 -> background3 > -0.08 (peso 0.0233)

======================================================================

Removida aresta background6 <= 0.10 -> background3 > -0.08 (peso 0.0112)
Mantida aresta background3 > -0.08 -> background6 <= 0.10 (peso 0.0202)

======================================================================

Removida aresta background1 <= 0.08 -> F6 <= -0.25 (peso 0.0078)
Mantida aresta F6 <= -0.25 -> background1 <= 0.08 (peso 0.0114)

======================================================================

Removida aresta background3 <= 0.09 -> background1 <= 0.08 (peso 0.0078)
Mantida aresta background1 <= 0.08 -> background3 <= 0.09 (peso 0.0089)

======================================================================

Removida aresta background2 <= 0.07 -> F3 <= -0.23 (peso 0.0038)
Mantida aresta F3 <= -0.23 -> background2 <= 0.07 (peso 0.0046)

======================================================================

Removida aresta F3 <= -0.23 -> background6 <= 0.08 (peso 0.0062)
Mantida aresta background6 <= 0.08 -> F3 <= -0.23 (peso 0.0080)

======================================================================

Removida aresta background2 > -0.06 -> F2 <= -0.23 (peso 0.0031)
Mantida aresta F2 <= -0.23 -> background2 > -0.06 (peso 0.0046)

======================================================================

Removida aresta background4 <= 0.09 -> F2 <= -0.23 (peso 0.0017)
Mantida aresta F2 <= -0.23 -> background4 <= 0.09 (peso 0.0046)

======================================================================

Removida aresta F2 <= -0.23 -> background5 > -0.08 (peso 0.0052)
Mantida aresta background5 > -0.08 -> F2 <= -0.23 (peso 0.0072)

======================================================================

Removida aresta background5 > -0.08 -> background6 > -0.09 (peso 0.0060)
Mantida aresta background6 > -0.09 -> background5 > -0.08 (peso 0.0101)

======================================================================

Removida aresta background6 > -0.09 -> background5 <= 0.08 (peso 0.0050)
Mantida aresta background5 <= 0.08 -> background6 > -0.09 (peso 0.0062)

======================================================================

Removida aresta background6 > -0.09 -> background3 <= 0.09 (peso 0.0059)
Mantida aresta background3 <= 0.09 -> background6 > -0.09 (peso 0.0067)

======================================================================

Removida aresta background3 > -0.09 -> background6 <= 0.08 (peso 0.0061)
Mantida aresta background6 <= 0.08 -> background3 > -0.09 (peso 0.0081)

======================================================================

Removida aresta background6 <= 0.08 -> background3 <= 0.07 (peso 0.0078)
Mantida aresta background3 <= 0.07 -> background6 <= 0.08 (peso 0.0174)

======================================================================

Removida aresta background3 <= 0.07 -> background3 > -0.09 (peso 0.0061)
Mantida aresta background3 > -0.09 -> background3 <= 0.07 (peso 0.0079)

======================================================================

Removida aresta background6 > -0.10 -> background3 > -0.09 (peso 0.0057)
Mantida aresta background3 > -0.09 -> background6 > -0.10 (peso 0.0072)

======================================================================

Removida aresta background6 > -0.10 -> background3 <= 0.07 (peso 0.0071)
Mantida aresta background3 <= 0.07 -> background6 > -0.10 (peso 0.0078)

======================================================================

Removida aresta background3 <= 0.09 -> background3 <= 0.07 (peso 0.0160)
Mantida aresta background3 <= 0.07 -> background3 <= 0.09 (peso 0.0224)

======================================================================

Removida aresta F6 <= -0.25 -> background6 > -0.10 (peso 0.0050)
Mantida aresta background6 > -0.10 -> F6 <= -0.25 (peso 0.0054)

======================================================================

Removida aresta background5 <= 0.08 -> background3 <= 0.09 (peso 0.0064)
Mantida aresta background3 <= 0.09 -> background5 <= 0.08 (peso 0.0079)

======================================================================

Removida aresta background5 <= 0.08 -> background4 <= 0.08 (peso 0.0041)
Mantida aresta background4 <= 0.08 -> background5 <= 0.08 (peso 0.0078)

======================================================================

Removida aresta background3 <= 0.09 -> background5 > -0.08 (peso 0.0057)
Mantida aresta background5 > -0.08 -> background3 <= 0.09 (peso 0.0079)

======================================================================

Removida aresta background5 > -0.08 -> background2 <= 0.07 (peso 0.0052)
Mantida aresta background2 <= 0.07 -> background5 > -0.08 (peso 0.0058)

======================================================================

Removida aresta background4 > 0.09 -> F6 <= -0.25 (peso 0.0035)
Mantida aresta F6 <= -0.25 -> background4 > 0.09 (peso 0.0044)

======================================================================

Removida aresta background4 > 0.08 -> background4 > 0.09 (peso 0.0073)
Mantida aresta background4 > 0.09 -> background4 > 0.08 (peso 0.0108)

======================================================================

Removida aresta background4 > 0.09 -> background4 <= 0.08 (peso 0.0033)
Mantida aresta background4 <= 0.08 -> background4 > 0.09 (peso 0.0047)

======================================================================

Removida aresta background5 > 0.08 -> background4 > 0.09 (peso 0.0034)
Mantida aresta background4 > 0.09 -> background5 > 0.08 (peso 0.0037)

======================================================================

Removida aresta background2 <= -0.06 -> background4 > 0.08 (peso 0.0028)
Mantida aresta background4 > 0.08 -> background2 <= -0.06 (peso 0.0036)

======================================================================

Removida aresta background1 <= -0.08 -> background4 > 0.08 (peso 0.0021)
Mantida aresta background4 > 0.08 -> background1 <= -0.08 (peso 0.0028)

======================================================================

Removida aresta background2 <= -0.06 -> background1 <= -0.08 (peso 0.0028)
Mantida aresta background1 <= -0.08 -> background2 <= -0.06 (peso 0.0053)

======================================================================

Removida aresta background2 <= -0.06 -> background2 > -0.06 (peso 0.0029)
Mantida aresta background2 > -0.06 -> background2 <= -0.06 (peso 0.0059)

======================================================================

Removida aresta background6 > 0.08 -> background3 > 0.07 (peso 0.0047)
Mantida aresta background3 > 0.07 -> background6 > 0.08 (peso 0.0077)

======================================================================

Removida aresta background6 > 0.08 -> background6 <= -0.09 (peso 0.0021)

,Predicate_Cov_Seed_0,Predicate_Cov_Seed_1,Predicate_Cov_Seed_2,Predicate_Cov_Seed_3
0,F1 > -0.71,F1 > -0.71,F1 > -0.71,F1 > -0.69
1,F1 > -0.69,F1 > -0.69,F1 <= 0.83,F1 > -0.71
2,F1 <= 0.83,F1 <= 0.83,F5 > -0.54,F1 <= 0.83
3,F5 > -0.54,F5 > -0.54,F1 > -0.69,F5 > -0.54
4,F5 <= 0.61,F5 <= 0.61,F5 <= 0.61,F5 <= 0.61
...,...,...,...,...
72,background5 > -0.10,F5 > 0.24,background6 <= -0.10,F5 > 0.24
73,background3 <= -0.08,background3 <= -0.09,F5 > 0.24,Class_A
74,background6 > 0.10,Class_A,Class_A,Class_B
75,Class_A,Class_B,Class_B,NaN
76,Class_B,NaN,NaN,NaN

In [18]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_cov_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df = lrc_summed_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_cov = lrc_summed_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_cov = lrc_summed_unique_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_cov

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,F1 > -0.71,12.562828,F1,-0.71,>
1,F5 > -0.54,9.489913,F5,-0.54,>
2,F2 > -0.45,2.418118,F2,-0.45,>
3,F4 > -0.24,2.360092,F4,-0.24,>
4,F6 > -0.25,2.218108,F6,-0.25,>
5,F3 > -0.43,2.128705,F3,-0.43,>
6,background4 > -0.09,0.241515,background4,-0.09,>
7,background3 > -0.08,0.189226,background3,-0.08,>
8,background1 > -0.10,0.174815,background1,-0.10,>
9,background6 <= 0.10,0.172316,background6,0.10,<=
10,background5 <= 0.08,0.140052,background5,0.08,<=
11,background2 > -0.08,0.119811,background2,-0.08,>
12,Class_B,0.000000,None,None,None

# **Perturbation**

In [12]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = pd.Series(y_pred) # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=svm_model[3],
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        #perturbation_value=0,
        perturbation_mode='mean', # valores entre 'mean' ou 'min'
        stats_source='full', # full indica usar todas as amostras para calcular estatísticas enquanto que 'fold' usa apenas as amostras do fold atual
        #metric='mean_abs_diff',   # Média com sinal (pode ser negativo)
        aim='classification',
        metric='probability_shift', 
        verbose=True
    )

    # Remove todos os valores iguais a zero de todos os bags em perm_results[bag]["Permutation"] e salva como perm_results_thresholded
    # pert_results_seed_thresholded = {}
    # for bag, df in perm_results_seed.items():
    #     # Verifica se é um DataFrame e se a coluna 'Permutation' existe
    #     if isinstance(df, pd.DataFrame) and 'Permutation' in df.columns:
    #         filtered_df = df[df['Permutation'] > 0].copy()
    #         pert_results_seed_thresholded[bag] = filtered_df
    #     else:
    #         # Se não for DataFrame esperado, apenas copia
    #         pert_results_seed_thresholded[bag] = df

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graphv2(
        bags_result=all_results_pert[seed]['bags_result'],
        predicate_ranking_dict=all_results_pert[seed]['pert_results_dict'],
        metric_column='Perturbation',  # ou 'Covariance' se mudar a métrica
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 75 | Descartados: 21
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
======================================================================
PERTURBATION IMPORTANCE PARA PREDICADOS
======================================================================
Tipo de tarefa (aim): classification
Modo de perturbação: mean
Fonte das estatísticas: full
Métrica: probability_shift
Total de folds: 10


[Bag_1] Processando 73 predicados...
  Predicado: F1 > -0.71 (n=130)
    Zona: 50 colunas
    Importance: 0.100185
  Predicado: F1 <= -0.69 (n=65)
    Zona: 50 colunas
    Importance: 0.246273
  Predicado: F1 > -0.69 (n=103)
    Zona: 50 colunas
    Importance: 0.063367
  Predicado: F1 <= 0.22 (n=100)
    Zona: 50 colunas
    Importance: 0.213660
  Predicado: F1 > 0.22 (n=68)
    Zona: 50 colunas
    Importance: 0.017185
  Predicado: F1 <= 0.83 (n=135)
    Zona: 50 colunas
    Importance: 0.162277
  Predicado: background1 > -0.10 (n=144)
    Zona: 50 colunas
    Importance: 0.000094
  Predicado: background1 <= -0.08 (n=58)
    Zona: 50 colunas
    Importance: 0.000092
  Predicado: background1 > -0.08 (n=110)
    Zona: 50 colunas
    Importance: 0.000088
  Predicado: background1 <= 0.08 (n=90)
    Zona: 50 colunas
    Importance: 0.000082
  Predicado: background1 > 0.08 (n=78)
    Zona: 50 colunas
    Importance: 0.000098
  Predicado: background1 <= 0.10 (n=135)
    Zona: 50 colunas
    Importance: 0.000090
  Predicado: F2 > -0.45 (n=134)
    Zona: 50 colunas
    Importance: 0.002487
  Predicado: F2 <= -0.23 (n=66)
    Zona: 50 colunas
    Importance: 0.003370
  Predicado: F2 > -0.23 (n=102)
    Zona: 50 colunas
    Importance: 0.002875
  Predicado: F2 <= 0.17 (n=101)
    Zona: 50 colunas
    Importance: 0.002373
  Predicado: F2 > 0.17 (n=67)
    Zona: 50 colunas
    Importance: 0.004119
  Predicado: F2 <= 0.40 (n=132)
    Zona: 50 colunas
    Importance: 0.003072
  Predicado: background2 > -0.08 (n=133)
    Zona: 15 colunas
    Importance: 0.000030
  Predicado: background2 <= -0.06 (n=71)
    Zona: 15 colunas
    Importance: 0.000032
  Predicado: background2 > -0.06 (n=97)
    Zona: 15 colunas
    Importance: 0.000034
  Predicado: background2 <= 0.07 (n=108)
    Zona: 15 colunas
    Importance: 0.000027
  Predicado: background2 > 0.07 (n=60)
    Zona: 15 colunas
    Importance: 0.000045
  Predicado: background2 <= 0.08 (n=137)
    Zona: 15 colunas
    Importance: 0.000029
  Predicado: F3 > -0.43 (n=131)
    Zona: 50 colunas
    Importance: 0.003244
  Predicado: F3 <= -0.23 (n=68)
    Zona: 50 colunas
    Importance: 0.003497
  Predicado: F3 > -0.23 (n=100)
    Zona: 50 colunas
    Importance: 0.002925
  Predicado: F3 <= 0.14 (n=106)
    Zona: 50 colunas
    Importance: 0.002457
  Predicado: F3 > 0.14 (n=62)
    Zona: 50 colunas
    Importance: 0.004353
  Predicado: F3 <= 0.44 (n=133)
    Zona: 50 colunas
    Importance: 0.002593
  Predicado: background3 > -0.09 (n=128)
    Zona: 35 colunas
    Importance: 0.000051
  Predicado: background3 <= -0.08 (n=60)
    Zona: 35 colunas
    Importance: 0.000061
  Predicado: background3 > -0.08 (n=108)
    Zona: 35 colunas
    Importance: 0.000052
  Predicado: background3 <= 0.07 (n=100)
    Zona: 35 colunas
    Importance: 0.000056
  Predicado: background3 > 0.07 (n=68)
    Zona: 35 colunas
    Importance: 0.000055
  Predicado: background3 <= 0.09 (n=131)
    Zona: 35 colunas
    Importance: 0.000055
  Predicado: F4 > -0.47 (n=132)
    Zona: 50 colunas
    Importance: 0.002026
  Predicado: F4 <= -0.24 (n=70)
    Zona: 50 colunas
    Importance: 0.002161
  Predicado: F4 > -0.24 (n=98)
    Zona: 50 colunas
    Importance: 0.002377
  Predicado: F4 <= 0.18 (n=102)
    Zona: 50 colunas
    Importance: 0.001613
  Predicado: F4 > 0.18 (n=66)
    Zona: 50 colunas
    Importance: 0.003327
  Predicado: F4 <= 0.50 (n=136)
    Zona: 50 colunas
    Importance: 0.001710
  Predicado: background4 > -0.09 (n=132)
    Zona: 30 colunas
    Importance: 0.000057
  Predicado: background4 <= -0.07 (n=71)
    Zona: 30 colunas
    Importance: 0.000059
  Predicado: background4 > -0.07 (n=97)
    Zona: 30 colunas
    Importance: 0.000058
  Predicado: background4 <= 0.08 (n=108)
    Zona: 30 colunas
    Importance: 0.000053
  Predicado: background4 > 0.08 (n=60)
    Zona: 30 colunas
    Importance: 0.000069
  Predicado: background4 <= 0.09 (n=118)
    Zona: 30 colunas
    Importance: 0.000051
  Predicado: background4 > 0.09 (n=50)
    Zona: 30 colunas
    Importance: 0.000076
  Predicado: F5 > -0.54 (n=135)
    Zona: 45 colunas
    Importance: 0.015150
  Predicado: F5 <= -0.52 (n=61)
    Zona: 45 colunas
    Importance: 0.035236
  Predicado: F5 > -0.52 (n=107)
    Zona: 45 colunas
    Importance: 0.010373
  Predicado: F5 <= 0.24 (n=97)
    Zona: 45 colunas
    Importance: 0.026371
  Predicado: F5 > 0.24 (n=71)
    Zona: 45 colunas
    Importance: 0.009878
  Predicado: F5 <= 0.61 (n=135)
    Zona: 45 colunas
    Importance: 0.021673
  Predicado: background5 > -0.10 (n=141)
    Zona: 32 colunas
    Importance: 0.000084
  Predicado: background5 <= -0.08 (n=66)
    Zona: 32 colunas
    Importance: 0.000061
  Predicado: background5 > -0.08 (n=102)
    Zona: 32 colunas
    Importance: 0.000095
  Predicado: background5 <= 0.08 (n=108)
    Zona: 32 colunas
    Importance: 0.000064
  Predicado: background5 > 0.08 (n=60)
    Zona: 32 colunas
    Importance: 0.000113
  Predicado: background5 <= 0.10 (n=140)
    Zona: 32 colunas
    Importance: 0.000061
  Predicado: F6 > -0.42 (n=133)
    Zona: 38 colunas
    Importance: 0.001999
  Predicado: F6 <= -0.25 (n=68)
    Zona: 38 colunas
    Importance: 0.005745
  Predicado: F6 > -0.25 (n=100)
    Zona: 38 colunas
    Importance: 0.002084
  Predicado: F6 <= 0.13 (n=106)
    Zona: 38 colunas
    Importance: 0.003973
  Predicado: F6 > 0.13 (n=62)
    Zona: 38 colunas
    Importance: 0.002869
  Predicado: F6 <= 0.42 (n=139)
    Zona: 38 colunas
    Importance: 0.003539
  Predicado: background6 > -0.10 (n=130)
    Zona: 55 colunas
    Importance: 0.000107
  Predicado: background6 <= -0.09 (n=60)
    Zona: 55 colunas
    Importance: 0.000116
  Predicado: background6 > -0.09 (n=108)
    Zona: 55 colunas
    Importance: 0.000116
  Predicado: background6 <= 0.08 (n=92)
    Zona: 55 colunas
    Importance: 0.000111
  Predicado: background6 > 0.08 (n=76)
    Zona: 55 colunas
    Importance: 0.000122
  Predicado: background6 <= 0.10 (n=127)
    Zona: 55 colunas
    Importance: 0.000100

[Bag_2] Processando 74 predicados...
  Predicado: F1 > -0.71 (n=133)
    Zona: 50 colunas
    Importance: 0.098014
  Predicado: F1 <= -0.69 (n=61)
    Zona: 50 colunas
    Importance: 0.246714
  Predicado: F1 > -0.69 (n=107)
    Zona: 50 colunas
    Importance: 0.058046
  Predicado: F1 <= 0.22 (n=101)
    Zona: 50 colunas
    Importance: 0.199665
  Predicado: F1 > 0.22 (n=67)
    Zona: 50 colunas
    Importance: 0.016334
  Predicado: F1 <= 0.83 (n=137)
    Zona: 50 colunas
    Importance: 0.150968
  Predicado: background1 > -0.10 (n=142)
    Zona: 50 colunas
    Importance: 0.000091
  Predicado: background1 <= -0.08 (n=59)
    Zona: 50 colunas
    Importance: 0.000091
  Predicado: background1 > -0.08 (n=109)
    Zona: 50 colunas
    Importance: 0.000085
  Predicado: background1 <= 0.08 (n=89)
    Zona: 50 colunas
    Importance: 0.000083
  Predicado: background1 > 0.08 (n=79)
    Zona: 50 colunas
    Importance: 0.000092
  Predicado: background1 <= 0.10 (n=133)
    Zona: 50 colunas
    Importance: 0.000086
  Predicado: F2 > -0.45 (n=132)
    Zona: 50 colunas
    Importance: 0.002798
  Predicado: F2 <= -0.23 (n=69)
    Zona: 50 colunas
    Importance: 0.002169
  Predicado: F2 > -0.23 (n=99)
    Zona: 50 colunas
    Importance: 0.003274
  Predicado: F2 <= 0.17 (n=99)
    Zona: 50 colunas
    Importance: 0.001670
  Predicado: F2 > 0.17 (n=69)
    Zona: 50 colunas
    Importance: 0.004471
  Predicado: F2 <= 0.40 (n=129)
    Zona: 50 colunas
    Importance: 0.002478
  Predicado: background2 > -0.08 (n=135)
    Zona: 15 colunas
    Importance: 0.000033
  Predicado: background2 <= -0.06 (n=73)
    Zona: 15 colunas
    Importance: 0.000025
  Predicado: background2 > -0.06 (n=95)
    Zona: 15 colunas
    Importance: 0.000037
  Predicado: background2 <= 0.07 (n=111)
    Zona: 15 colunas
    Importance: 0.000024
  Predicado: background2 > 0.07 (n=57)
    Zona: 15 colunas
    Importance: 0.000047
  Predicado: background2 <= 0.08 (n=139)
    Zona: 15 colunas
    Importance: 0.000027
  Predicado: F3 > -0.43 (n=136)
    Zona: 50 colunas
    Importance: 0.003119
  Predicado: F3 <= -0.23 (n=64)
    Zona: 50 colunas
    Importance: 0.003785
  Predicado: F3 > -0.23 (n=104)
    Zona: 50 colunas
    Importance: 0.002795
  Predicado: F3 <= 0.14 (n=101)
    Zona: 50 colunas
    Importance: 0.002629
  Predicado: F3 > 0.14 (n=67)
    Zona: 50 colunas
    Importance: 0.003991
  Predicado: F3 <= 0.44 (n=135)
    Zona: 50 colunas
    Importance: 0.002682
  Predicado: background3 > -0.09 (n=129)
    Zona: 35 colunas
    Importance: 0.000055
  Predicado: background3 <= -0.08 (n=57)
    Zona: 35 colunas
    Importance: 0.000059
  Predicado: background3 > -0.08 (n=111)
    Zona: 35 colunas
    Importance: 0.000054
  Predicado: background3 <= 0.07 (n=100)
    Zona: 35 colunas
    Importance: 0.000054
  Predicado: background3 > 0.07 (n=68)
    Zona: 35 colunas
    Importance: 0.000058
  Predicado: background3 <= 0.09 (n=134)
    Zona: 35 colunas
    Importance: 0.000053
  Predicado: F4 > -0.47 (n=135)
    Zona: 50 colunas
    Importance: 0.001899
  Predicado: F4 <= -0.24 (n=62)
    Zona: 50 colunas
    Importance: 0.002297
  Predicado: F4 > -0.24 (n=106)
    Zona: 50 colunas
    Importance: 0.002152
  Predicado: F4 <= 0.18 (n=100)
    Zona: 50 colunas
    Importance: 0.001627
  Predicado: F4 > 0.18 (n=68)
    Zona: 50 colunas
    Importance: 0.003058
  Predicado: F4 <= 0.50 (n=133)
    Zona: 50 colunas
    Importance: 0.001627
  Predicado: background4 > -0.09 (n=131)
    Zona: 30 colunas
    Importance: 0.000057
  Predicado: background4 <= -0.07 (n=68)
    Zona: 30 colunas
    Importance: 0.000059
  Predicado: background4 > -0.07 (n=100)
    Zona: 30 colunas
    Importance: 0.000059
  Predicado: background4 <= 0.08 (n=105)
    Zona: 30 colunas
    Importance: 0.000050
  Predicado: background4 > 0.08 (n=63)
    Zona: 30 colunas
    Importance: 0.000073
  Predicado: background4 <= 0.09 (n=116)
    Zona: 30 colunas
    Importance: 0.000050
  Predicado: background4 > 0.09 (n=52)
    Zona: 30 colunas
    Importance: 0.000079
  Predicado: F5 > -0.54 (n=137)
    Zona: 45 colunas
    Importance: 0.015973
  Predicado: F5 <= -0.52 (n=61)
    Zona: 45 colunas
    Importance: 0.038960
  Predicado: F5 > -0.52 (n=107)
    Zona: 45 colunas
    Importance: 0.010750
  Predicado: F5 <= 0.24 (n=98)
    Zona: 45 colunas
    Importance: 0.029048
  Predicado: F5 > 0.24 (n=70)
    Zona: 45 colunas
    Importance: 0.009715
  Predicado: F5 <= 0.61 (n=134)
    Zona: 45 colunas
    Importance: 0.024030
  Predicado: background5 > -0.10 (n=142)
    Zona: 32 colunas
    Importance: 0.000084
  Predicado: background5 <= -0.08 (n=63)
    Zona: 32 colunas
    Importance: 0.000053
  Predicado: background5 > -0.08 (n=105)
    Zona: 32 colunas
    Importance: 0.000096
  Predicado: background5 <= 0.08 (n=103)
    Zona: 32 colunas
    Importance: 0.000060
  Predicado: background5 > 0.08 (n=65)
    Zona: 32 colunas
    Importance: 0.000112
  Predicado: background5 <= 0.10 (n=138)
    Zona: 32 colunas
    Importance: 0.000058
  Predicado: F6 > -0.42 (n=132)
    Zona: 38 colunas
    Importance: 0.002428
  Predicado: F6 <= -0.25 (n=65)
    Zona: 38 colunas
    Importance: 0.003482
  Predicado: F6 > -0.25 (n=103)
    Zona: 38 colunas
    Importance: 0.002472
  Predicado: F6 <= 0.13 (n=100)
    Zona: 38 colunas
    Importance: 0.002561
  Predicado: F6 > 0.13 (n=68)
    Zona: 38 colunas
    Importance: 0.003307
  Predicado: F6 <= 0.42 (n=133)
    Zona: 38 colunas
    Importance: 0.002513
  Predicado: background6 > -0.10 (n=130)
    Zona: 55 colunas
    Importance: 0.000107
  Predicado: background6 <= -0.09 (n=64)
    Zona: 55 colunas
    Importance: 0.000100
  Predicado: background6 > -0.09 (n=104)
    Zona: 55 colunas
    Importance: 0.000115
  Predicado: background6 <= 0.08 (n=95)
    Zona: 55 colunas
    Importance: 0.000103
  Predicado: background6 > 0.08 (n=73)
    Zona: 55 colunas
    Importance: 0.000117
  Predicado: background6 <= 0.10 (n=126)
    Zona: 55 colunas
    Importance: 0.000093
  Predicado: background6 > 0.10 (n=42)
    Zona: 55 colunas
    Importance: 0.000157

[Bag_3] Processando 74 predicados...
  Predicado: F1 > -0.71 (n=128)
    Zona: 50 colunas
    Importance: 0.099989
  Predicado: F1 <= -0.69 (n=65)
    Zona: 50 colunas
    Importance: 0.256418
  Predicado: F1 > -0.69 (n=103)
    Zona: 50 colunas
    Importance: 0.065402
  Predicado: F1 <= 0.22 (n=103)
    Zona: 50 colunas
    Importance: 0.217832
  Predicado: F1 > 0.22 (n=65)
    Zona: 50 colunas
    Importance: 0.014876
  Predicado: F1 <= 0.83 (n=135)
    Zona: 50 colunas
    Importance: 0.168809
  Predicado: background1 > -0.10 (n=139)
    Zona: 50 colunas
    Importance: 0.000091
  Predicado: background1 <= -0.08 (n=63)
    Zona: 50 colunas
    Importance: 0.000088
  Predicado: background1 > -0.08 (n=105)
    Zona: 50 colunas
    Importance: 0.000088
  Predicado: background1 <= 0.08 (n=91)
    Zona: 50 colunas
    Importance: 0.000082
  Predicado: background1 > 0.08 (n=77)
    Zona: 50 colunas
    Importance: 0.000095
  Predicado: background1 <= 0.10 (n=135)
    Zona: 50 colunas
    Importance: 0.000086
  Predicado: F2 > -0.45 (n=136)
    Zona: 50 colunas
    Importance: 0.002482
  Predicado: F2 <= -0.23 (n=67)
    Zona: 50 colunas
    Importance: 0.003192
  Predicado: F2 > -0.23 (n=101)
    Zona: 50 colunas
    Importance: 0.002911
  Predicado: F2 <= 0.17 (n=104)
    Zona: 50 colunas
    Importance: 0.002241
  Predicado: F2 > 0.17 (n=64)
    Zona: 50 colunas
    Importance: 0.004295
  Predicado: F2 <= 0.40 (n=136)
    Zona: 50 colunas
    Importance: 0.002912
  Predicado: background2 > -0.08 (n=134)
    Zona: 15 colunas
    Importance: 0.000031
  Predicado: background2 <= -0.06 (n=74)
    Zona: 15 colunas
    Importance: 0.000033
  Predicado: background2 > -0.06 (n=94)
    Zona: 15 colunas
    Importance: 0.000033
  Predicado: background2 <= 0.07 (n=111)
    Zona: 15 colunas
    Importance: 0.000029
  Predicado: background2 > 0.07 (n=57)
    Zona: 15 colunas
    Importance: 0.000042
  Predicado: background2 <= 0.08 (n=138)
    Zona: 15 colunas
    Importance: 0.000031
  Predicado: F3 > -0.43 (n=136)
    Zona: 50 colunas
    Importance: 0.003147
  Predicado: F3 <= -0.23 (n=65)
    Zona: 50 colunas
    Importance: 0.003011
  Predicado: F3 > -0.23 (n=103)
    Zona: 50 colunas
    Importance: 0.003202
  Predicado: F3 <= 0.14 (n=103)
    Zona: 50 colunas
    Importance: 0.002112
  Predicado: F3 > 0.14 (n=65)
    Zona: 50 colunas
    Importance: 0.004738
  Predicado: F3 <= 0.44 (n=135)
    Zona: 50 colunas
    Importance: 0.002350
  Predicado: background3 <= -0.09 (n=42)
    Zona: 35 colunas
    Importance: 0.000058
  Predicado: background3 > -0.09 (n=126)
    Zona: 35 colunas
    Importance: 0.000052
  Predicado: background3 <= -0.08 (n=62)
    Zona: 35 colunas
    Importance: 0.000059
  Predicado: background3 > -0.08 (n=106)
    Zona: 35 colunas
    Importance: 0.000051
  Predicado: background3 <= 0.07 (n=96)
    Zona: 35 colunas
    Importance: 0.000056
  Predicado: background3 > 0.07 (n=72)
    Zona: 35 colunas
    Importance: 0.000051
  Predicado: background3 <= 0.09 (n=132)
    Zona: 35 colunas
    Importance: 0.000053
  Predicado: F4 > -0.47 (n=132)
    Zona: 50 colunas
    Importance: 0.001617
  Predicado: F4 <= -0.24 (n=72)
    Zona: 50 colunas
    Importance: 0.001985
  Predicado: F4 > -0.24 (n=96)
    Zona: 50 colunas
    Importance: 0.001915
  Predicado: F4 <= 0.18 (n=108)
    Zona: 50 colunas
    Importance: 0.001505
  Predicado: F4 > 0.18 (n=60)
    Zona: 50 colunas
    Importance: 0.002737
  Predicado: F4 <= 0.50 (n=139)
    Zona: 50 colunas
    Importance: 0.001484
  Predicado: background4 > -0.09 (n=131)
    Zona: 30 colunas
    Importance: 0.000057
  Predicado: background4 <= -0.07 (n=70)
    Zona: 30 colunas
    Importance: 0.000056
  Predicado: background4 > -0.07 (n=98)
    Zona: 30 colunas
    Importance: 0.000058
  Predicado: background4 <= 0.08 (n=106)
    Zona: 30 colunas
    Importance: 0.000051
  Predicado: background4 > 0.08 (n=62)
    Zona: 30 colunas
    Importance: 0.000067
  Predicado: background4 <= 0.09 (n=118)
    Zona: 30 colunas
    Importance: 0.000051
  Predicado: background4 > 0.09 (n=50)
    Zona: 30 colunas
    Importance: 0.000072
  Predicado: F5 > -0.54 (n=140)
    Zona: 45 colunas
    Importance: 0.015278
  Predicado: F5 <= -0.52 (n=61)
    Zona: 45 colunas
    Importance: 0.038217
  Predicado: F5 > -0.52 (n=107)
    Zona: 45 colunas
    Importance: 0.010022
  Predicado: F5 <= 0.24 (n=95)
    Zona: 45 colunas
    Importance: 0.028901
  Predicado: F5 > 0.24 (n=73)
    Zona: 45 colunas
    Importance: 0.009014
  Predicado: F5 <= 0.61 (n=133)
    Zona: 45 colunas
    Importance: 0.023598
  Predicado: background5 > -0.10 (n=140)
    Zona: 32 colunas
    Importance: 0.000080
  Predicado: background5 <= -0.08 (n=70)
    Zona: 32 colunas
    Importance: 0.000054
  Predicado: background5 > -0.08 (n=98)
    Zona: 32 colunas
    Importance: 0.000096
  Predicado: background5 <= 0.08 (n=106)
    Zona: 32 colunas
    Importance: 0.000061
  Predicado: background5 > 0.08 (n=62)
    Zona: 32 colunas
    Importance: 0.000107
  Predicado: background5 <= 0.10 (n=137)
    Zona: 32 colunas
    Importance: 0.000059
  Predicado: F6 > -0.42 (n=131)
    Zona: 38 colunas
    Importance: 0.002175
  Predicado: F6 <= -0.25 (n=63)
    Zona: 38 colunas
    Importance: 0.006297
  Predicado: F6 > -0.25 (n=105)
    Zona: 38 colunas
    Importance: 0.002287
  Predicado: F6 <= 0.13 (n=103)
    Zona: 38 colunas
    Importance: 0.004177
  Predicado: F6 > 0.13 (n=65)
    Zona: 38 colunas
    Importance: 0.003180
  Predicado: F6 <= 0.42 (n=137)
    Zona: 38 colunas
    Importance: 0.003567
  Predicado: background6 > -0.10 (n=129)
    Zona: 55 colunas
    Importance: 0.000102
  Predicado: background6 <= -0.09 (n=65)
    Zona: 55 colunas
    Importance: 0.000106
  Predicado: background6 > -0.09 (n=103)
    Zona: 55 colunas
    Importance: 0.000110
  Predicado: background6 <= 0.08 (n=98)
    Zona: 55 colunas
    Importance: 0.000106
  Predicado: background6 > 0.08 (n=70)
    Zona: 55 colunas
    Importance: 0.000111
  Predicado: background6 <= 0.10 (n=128)
    Zona: 55 colunas
    Importance: 0.000096

[Bag_4] Processando 75 predicados...
  Predicado: F1 > -0.71 (n=129)
    Zona: 50 colunas
    Importance: 0.109182
  Predicado: F1 <= -0.69 (n=68)
    Zona: 50 colunas
    Importance: 0.253578
  Predicado: F1 > -0.69 (n=100)
    Zona: 50 colunas
    Importance: 0.070613
  Predicado: F1 <= 0.22 (n=104)
    Zona: 50 colunas
    Importance: 0.223952
  Predicado: F1 > 0.22 (n=64)
    Zona: 50 colunas
    Importance: 0.015838

,Predicate_pert_Seed_0,Predicate_pert_Seed_1,Predicate_pert_Seed_2,Predicate_pert_Seed_3
0,F1 <= -0.69,F1 <= -0.69,F1 <= -0.69,F1 <= -0.69
1,F1 <= 0.22,F1 <= 0.22,F1 <= 0.22,F1 <= 0.22
2,F1 <= 0.83,F1 <= 0.83,F1 <= 0.83,F1 <= 0.83
3,F1 > -0.71,F1 > -0.71,F1 > -0.71,F1 > -0.71
4,F1 > -0.69,F1 > -0.69,F1 > -0.69,F1 > -0.69
...,...,...,...,...
74,background2 <= 0.07,background2 > -0.08,background2 <= -0.06,background2 <= -0.06
75,background2 <= 0.08,background2 <= 0.07,background2 <= 0.07,Class_A
76,background2 <= -0.06,Class_A,Class_A,Class_B
77,Class_A,Class_B,Class_B,NaN
78,Class_B,NaN,NaN,NaN

In [13]:
all_results_pert[0]['pert_results_dict']['Bag_9']

               Predicate  Perturbation
0            F1 <= -0.69      0.231785
1             F1 <= 0.22      0.203058
2             F1 <= 0.83      0.155918
3             F1 > -0.71      0.096820
4             F1 > -0.69      0.069788
..                   ...           ...
69   background2 > -0.06      0.000037
70   background2 > -0.08      0.000033
71   background2 <= 0.08      0.000026
72  background2 <= -0.06      0.000023
73   background2 <= 0.07      0.000022

[74 rows x 2 columns]

In [14]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_pert_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df = lrc_summed_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_pert = lrc_summed_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_pert = lrc_summed_unique_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_pert

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,F1 <= -0.69,19.512936,F1,-0.69,<=
1,F5 <= -0.52,2.772248,F5,-0.52,<=
2,F6 <= -0.25,0.286932,F6,-0.25,<=
3,F3 > 0.14,0.204081,F3,0.14,>
4,F2 > 0.17,0.173143,F2,0.17,>
5,F4 <= -0.24,0.120774,F4,-0.24,<=
6,background6 > 0.10,0.004396,background6,0.10,>
7,background1 > 0.08,0.003565,background1,0.08,>
8,background5 > 0.08,0.003470,background5,0.08,>
9,background4 > 0.09,0.002983,background4,0.09,>
10,background3 > -0.09,0.002233,background3,-0.09,>
11,background2 > 0.07,0.000618,background2,0.07,>
12,Class_B,0.000000,None,None,None

In [19]:
import numpy as np

max_len = max(
    len(pvector_unique_df['Zone']),
    len(shap_unique_df['Zone']),
    len(permutation_unique_df['Zone']),
    len(lrc_summed_unique_df_pert['Zone']),
    len(lrc_summed_unique_df_cov['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'SVM_pvector': pad_list(pvector_unique_df['Zone'], max_len),
    'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'Permutation': pad_list(permutation_unique_df['Zone'], max_len),
    'LRC_perturbation' : pad_list(lrc_summed_unique_df_pert['Zone'], max_len),
    'LRC_covariance' : pad_list(lrc_summed_unique_df_cov['Zone'], max_len),
})

features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

    SVM_pvector         Shap  Permutation LRC_perturbation LRC_covariance
0            F1           F1           F1               F1             F1
1            F5           F5           F5               F5             F5
2            F6           F3           F6               F6             F2
3            F3           F4           F3               F3             F4
4            F4           F2           F4               F2             F6
5            F2           F6           F2               F4             F3
6   background2  background1  background1      background6    background4
7   background1  background2  background2      background1    background3
8   background4  background6  background5      background5    background1
9   background6  background3  background4      background4    background6
10  background5  background5  background6      background3    background5
11  background3  background4  background3      background2    background2
12         None         None         None             None           None

In [20]:
import rbo

rbo_comparison = pd.DataFrame(columns=['Method_1', 'Method_2', 'RBO_Score'])
methods = features_importance.columns.tolist()
for i in range(len(methods)):
    for j in range(i + 1, len(methods)):
        method_1 = methods[i]
        method_2 = methods[j]
        list_1 = features_importance[method_1].tolist()
        list_2 = features_importance[method_2].tolist()
        rbo_score = rbo.RankingSimilarity(list_1, list_2).rbo(p=0.7, k=10)
        rbo_comparison = pd.concat([rbo_comparison, pd.DataFrame({
            'Method_1': [method_1],
            'Method_2': [method_2],
            'RBO_Score': [rbo_score]
        })], ignore_index=True)
rbo_comparison.sort_values(by='RBO_Score', ascending=False, inplace=True)
rbo_comparison.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_comparison

C:\Users\Usuario\AppData\Local\Temp\ipykernel_2796\3888930707.py:12: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

           Method_1          Method_2  RBO_Score
1       SVM_pvector       Permutation   0.963578
7       Permutation  LRC_perturbation   0.946084
2       SVM_pvector  LRC_perturbation   0.944162
4              Shap       Permutation   0.878279
0       SVM_pvector              Shap   0.874447
5              Shap  LRC_perturbation   0.870148
6              Shap    LRC_covariance   0.866349
3       SVM_pvector    LRC_covariance   0.842546
9  LRC_perturbation    LRC_covariance   0.840624
8       Permutation    LRC_covariance   0.839413